//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.subActividadWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="subActividadWS.subActividadWS")]
    public interface subActividadWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/AgregarSubActividadRequest", ReplyAction="http://webservices/subActividadWS/AgregarSubActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.subActividadWS.AgregarSubActividadResponse AgregarSubActividad(ProyectoEscritorio.subActividadWS.AgregarSubActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/AgregarSubActividadRequest", ReplyAction="http://webservices/subActividadWS/AgregarSubActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.AgregarSubActividadResponse> AgregarSubActividadAsync(ProyectoEscritorio.subActividadWS.AgregarSubActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/EliminarSubActividadRequest", ReplyAction="http://webservices/subActividadWS/EliminarSubActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.subActividadWS.EliminarSubActividadResponse EliminarSubActividad(ProyectoEscritorio.subActividadWS.EliminarSubActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/EliminarSubActividadRequest", ReplyAction="http://webservices/subActividadWS/EliminarSubActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EliminarSubActividadResponse> EliminarSubActividadAsync(ProyectoEscritorio.subActividadWS.EliminarSubActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/EliminarSubActividadesRequest", ReplyAction="http://webservices/subActividadWS/EliminarSubActividadesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.subActividadWS.EliminarSubActividadesResponse EliminarSubActividades(ProyectoEscritorio.subActividadWS.EliminarSubActividadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/EliminarSubActividadesRequest", ReplyAction="http://webservices/subActividadWS/EliminarSubActividadesResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EliminarSubActividadesResponse> EliminarSubActividadesAsync(ProyectoEscritorio.subActividadWS.EliminarSubActividadesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/EditarSubActividadRequest", ReplyAction="http://webservices/subActividadWS/EditarSubActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.subActividadWS.EditarSubActividadResponse EditarSubActividad(ProyectoEscritorio.subActividadWS.EditarSubActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/EditarSubActividadRequest", ReplyAction="http://webservices/subActividadWS/EditarSubActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EditarSubActividadResponse> EditarSubActividadAsync(ProyectoEscritorio.subActividadWS.EditarSubActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/SeleccionarSubActividadRequest", ReplyAction="http://webservices/subActividadWS/SeleccionarSubActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.subActividadWS.SeleccionarSubActividadResponse SeleccionarSubActividad(ProyectoEscritorio.subActividadWS.SeleccionarSubActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/SeleccionarSubActividadRequest", ReplyAction="http://webservices/subActividadWS/SeleccionarSubActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.SeleccionarSubActividadResponse> SeleccionarSubActividadAsync(ProyectoEscritorio.subActividadWS.SeleccionarSubActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/ObtenerSubActividadesDeActividadRequest", ReplyAction="http://webservices/subActividadWS/ObtenerSubActividadesDeActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadResponse ObtenerSubActividadesDeActividad(ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/ObtenerSubActividadesDeActividadRequest", ReplyAction="http://webservices/subActividadWS/ObtenerSubActividadesDeActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadResponse> ObtenerSubActividadesDeActividadAsync(ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/ObtenerSubActividadesDeUsuarioRequest", ReplyAction="http://webservices/subActividadWS/ObtenerSubActividadesDeUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioResponse ObtenerSubActividadesDeUsuario(ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/subActividadWS/ObtenerSubActividadesDeUsuarioRequest", ReplyAction="http://webservices/subActividadWS/ObtenerSubActividadesDeUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioResponse> ObtenerSubActividadesDeUsuarioAsync(ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarSubActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarSubActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idActividad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public AgregarSubActividadRequest() {
        }
        
        public AgregarSubActividadRequest(string descripcion, string vencimiento, string estado, int idActividad, int idUsuario) {
            this.descripcion = descripcion;
            this.vencimiento = vencimiento;
            this.estado = estado;
            this.idActividad = idActividad;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarSubActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarSubActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public AgregarSubActividadResponse() {
        }
        
        public AgregarSubActividadResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarSubActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarSubActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarSubActividadRequest() {
        }
        
        public EliminarSubActividadRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarSubActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarSubActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarSubActividadResponse() {
        }
        
        public EliminarSubActividadResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarSubActividades", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarSubActividadesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idActvidad;
        
        public EliminarSubActividadesRequest() {
        }
        
        public EliminarSubActividadesRequest(int idActvidad) {
            this.idActvidad = idActvidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarSubActividadesResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarSubActividadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarSubActividadesResponse() {
        }
        
        public EliminarSubActividadesResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarSubActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarSubActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idActividad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EditarSubActividadRequest() {
        }
        
        public EditarSubActividadRequest(string descripcion, string vencimiento, string estado, int idActividad, int idUsuario, int id) {
            this.descripcion = descripcion;
            this.vencimiento = vencimiento;
            this.estado = estado;
            this.idActividad = idActividad;
            this.idUsuario = idUsuario;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarSubActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarSubActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EditarSubActividadResponse() {
        }
        
        public EditarSubActividadResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class subActividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string estadoField;
        
        private int idField;
        
        private int idActividadField;
        
        private int idUsuarioField;
        
        private System.DateTime vencimientoField;
        
        private bool vencimientoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
                this.RaisePropertyChanged("idActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
                this.RaisePropertyChanged("vencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vencimientoSpecified {
            get {
                return this.vencimientoFieldSpecified;
            }
            set {
                this.vencimientoFieldSpecified = value;
                this.RaisePropertyChanged("vencimientoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarSubActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarSubActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarSubActividadRequest() {
        }
        
        public SeleccionarSubActividadRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarSubActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarSubActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.subActividadWS.subActividad @return;
        
        public SeleccionarSubActividadResponse() {
        }
        
        public SeleccionarSubActividadResponse(ProyectoEscritorio.subActividadWS.subActividad @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerSubActividadesDeActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerSubActividadesDeActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idActividad;
        
        public ObtenerSubActividadesDeActividadRequest() {
        }
        
        public ObtenerSubActividadesDeActividadRequest(int idActividad) {
            this.idActividad = idActividad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerSubActividadesDeActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerSubActividadesDeActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.subActividadWS.subActividad[] @return;
        
        public ObtenerSubActividadesDeActividadResponse() {
        }
        
        public ObtenerSubActividadesDeActividadResponse(ProyectoEscritorio.subActividadWS.subActividad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerSubActividadesDeUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerSubActividadesDeUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public ObtenerSubActividadesDeUsuarioRequest() {
        }
        
        public ObtenerSubActividadesDeUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerSubActividadesDeUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerSubActividadesDeUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.subActividadWS.subActividad[] @return;
        
        public ObtenerSubActividadesDeUsuarioResponse() {
        }
        
        public ObtenerSubActividadesDeUsuarioResponse(ProyectoEscritorio.subActividadWS.subActividad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface subActividadWSChannel : ProyectoEscritorio.subActividadWS.subActividadWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class subActividadWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.subActividadWS.subActividadWS>, ProyectoEscritorio.subActividadWS.subActividadWS {
        
        public subActividadWSClient() {
        }
        
        public subActividadWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public subActividadWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public subActividadWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public subActividadWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.subActividadWS.AgregarSubActividadResponse ProyectoEscritorio.subActividadWS.subActividadWS.AgregarSubActividad(ProyectoEscritorio.subActividadWS.AgregarSubActividadRequest request) {
            return base.Channel.AgregarSubActividad(request);
        }
        
        public int AgregarSubActividad(string descripcion, string vencimiento, string estado, int idActividad, int idUsuario) {
            ProyectoEscritorio.subActividadWS.AgregarSubActividadRequest inValue = new ProyectoEscritorio.subActividadWS.AgregarSubActividadRequest();
            inValue.descripcion = descripcion;
            inValue.vencimiento = vencimiento;
            inValue.estado = estado;
            inValue.idActividad = idActividad;
            inValue.idUsuario = idUsuario;
            ProyectoEscritorio.subActividadWS.AgregarSubActividadResponse retVal = ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).AgregarSubActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.AgregarSubActividadResponse> ProyectoEscritorio.subActividadWS.subActividadWS.AgregarSubActividadAsync(ProyectoEscritorio.subActividadWS.AgregarSubActividadRequest request) {
            return base.Channel.AgregarSubActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.AgregarSubActividadResponse> AgregarSubActividadAsync(string descripcion, string vencimiento, string estado, int idActividad, int idUsuario) {
            ProyectoEscritorio.subActividadWS.AgregarSubActividadRequest inValue = new ProyectoEscritorio.subActividadWS.AgregarSubActividadRequest();
            inValue.descripcion = descripcion;
            inValue.vencimiento = vencimiento;
            inValue.estado = estado;
            inValue.idActividad = idActividad;
            inValue.idUsuario = idUsuario;
            return ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).AgregarSubActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.subActividadWS.EliminarSubActividadResponse ProyectoEscritorio.subActividadWS.subActividadWS.EliminarSubActividad(ProyectoEscritorio.subActividadWS.EliminarSubActividadRequest request) {
            return base.Channel.EliminarSubActividad(request);
        }
        
        public bool EliminarSubActividad(int id) {
            ProyectoEscritorio.subActividadWS.EliminarSubActividadRequest inValue = new ProyectoEscritorio.subActividadWS.EliminarSubActividadRequest();
            inValue.id = id;
            ProyectoEscritorio.subActividadWS.EliminarSubActividadResponse retVal = ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).EliminarSubActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EliminarSubActividadResponse> ProyectoEscritorio.subActividadWS.subActividadWS.EliminarSubActividadAsync(ProyectoEscritorio.subActividadWS.EliminarSubActividadRequest request) {
            return base.Channel.EliminarSubActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EliminarSubActividadResponse> EliminarSubActividadAsync(int id) {
            ProyectoEscritorio.subActividadWS.EliminarSubActividadRequest inValue = new ProyectoEscritorio.subActividadWS.EliminarSubActividadRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).EliminarSubActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.subActividadWS.EliminarSubActividadesResponse ProyectoEscritorio.subActividadWS.subActividadWS.EliminarSubActividades(ProyectoEscritorio.subActividadWS.EliminarSubActividadesRequest request) {
            return base.Channel.EliminarSubActividades(request);
        }
        
        public bool EliminarSubActividades(int idActvidad) {
            ProyectoEscritorio.subActividadWS.EliminarSubActividadesRequest inValue = new ProyectoEscritorio.subActividadWS.EliminarSubActividadesRequest();
            inValue.idActvidad = idActvidad;
            ProyectoEscritorio.subActividadWS.EliminarSubActividadesResponse retVal = ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).EliminarSubActividades(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EliminarSubActividadesResponse> ProyectoEscritorio.subActividadWS.subActividadWS.EliminarSubActividadesAsync(ProyectoEscritorio.subActividadWS.EliminarSubActividadesRequest request) {
            return base.Channel.EliminarSubActividadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EliminarSubActividadesResponse> EliminarSubActividadesAsync(int idActvidad) {
            ProyectoEscritorio.subActividadWS.EliminarSubActividadesRequest inValue = new ProyectoEscritorio.subActividadWS.EliminarSubActividadesRequest();
            inValue.idActvidad = idActvidad;
            return ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).EliminarSubActividadesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.subActividadWS.EditarSubActividadResponse ProyectoEscritorio.subActividadWS.subActividadWS.EditarSubActividad(ProyectoEscritorio.subActividadWS.EditarSubActividadRequest request) {
            return base.Channel.EditarSubActividad(request);
        }
        
        public bool EditarSubActividad(string descripcion, string vencimiento, string estado, int idActividad, int idUsuario, int id) {
            ProyectoEscritorio.subActividadWS.EditarSubActividadRequest inValue = new ProyectoEscritorio.subActividadWS.EditarSubActividadRequest();
            inValue.descripcion = descripcion;
            inValue.vencimiento = vencimiento;
            inValue.estado = estado;
            inValue.idActividad = idActividad;
            inValue.idUsuario = idUsuario;
            inValue.id = id;
            ProyectoEscritorio.subActividadWS.EditarSubActividadResponse retVal = ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).EditarSubActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EditarSubActividadResponse> ProyectoEscritorio.subActividadWS.subActividadWS.EditarSubActividadAsync(ProyectoEscritorio.subActividadWS.EditarSubActividadRequest request) {
            return base.Channel.EditarSubActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.EditarSubActividadResponse> EditarSubActividadAsync(string descripcion, string vencimiento, string estado, int idActividad, int idUsuario, int id) {
            ProyectoEscritorio.subActividadWS.EditarSubActividadRequest inValue = new ProyectoEscritorio.subActividadWS.EditarSubActividadRequest();
            inValue.descripcion = descripcion;
            inValue.vencimiento = vencimiento;
            inValue.estado = estado;
            inValue.idActividad = idActividad;
            inValue.idUsuario = idUsuario;
            inValue.id = id;
            return ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).EditarSubActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.subActividadWS.SeleccionarSubActividadResponse ProyectoEscritorio.subActividadWS.subActividadWS.SeleccionarSubActividad(ProyectoEscritorio.subActividadWS.SeleccionarSubActividadRequest request) {
            return base.Channel.SeleccionarSubActividad(request);
        }
        
        public ProyectoEscritorio.subActividadWS.subActividad SeleccionarSubActividad(int id) {
            ProyectoEscritorio.subActividadWS.SeleccionarSubActividadRequest inValue = new ProyectoEscritorio.subActividadWS.SeleccionarSubActividadRequest();
            inValue.id = id;
            ProyectoEscritorio.subActividadWS.SeleccionarSubActividadResponse retVal = ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).SeleccionarSubActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.SeleccionarSubActividadResponse> ProyectoEscritorio.subActividadWS.subActividadWS.SeleccionarSubActividadAsync(ProyectoEscritorio.subActividadWS.SeleccionarSubActividadRequest request) {
            return base.Channel.SeleccionarSubActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.SeleccionarSubActividadResponse> SeleccionarSubActividadAsync(int id) {
            ProyectoEscritorio.subActividadWS.SeleccionarSubActividadRequest inValue = new ProyectoEscritorio.subActividadWS.SeleccionarSubActividadRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).SeleccionarSubActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadResponse ProyectoEscritorio.subActividadWS.subActividadWS.ObtenerSubActividadesDeActividad(ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadRequest request) {
            return base.Channel.ObtenerSubActividadesDeActividad(request);
        }
        
        public ProyectoEscritorio.subActividadWS.subActividad[] ObtenerSubActividadesDeActividad(int idActividad) {
            ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadRequest inValue = new ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadRequest();
            inValue.idActividad = idActividad;
            ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadResponse retVal = ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).ObtenerSubActividadesDeActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadResponse> ProyectoEscritorio.subActividadWS.subActividadWS.ObtenerSubActividadesDeActividadAsync(ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadRequest request) {
            return base.Channel.ObtenerSubActividadesDeActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadResponse> ObtenerSubActividadesDeActividadAsync(int idActividad) {
            ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadRequest inValue = new ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeActividadRequest();
            inValue.idActividad = idActividad;
            return ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).ObtenerSubActividadesDeActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioResponse ProyectoEscritorio.subActividadWS.subActividadWS.ObtenerSubActividadesDeUsuario(ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioRequest request) {
            return base.Channel.ObtenerSubActividadesDeUsuario(request);
        }
        
        public ProyectoEscritorio.subActividadWS.subActividad[] ObtenerSubActividadesDeUsuario(int idUsuario) {
            ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioRequest inValue = new ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioResponse retVal = ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).ObtenerSubActividadesDeUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioResponse> ProyectoEscritorio.subActividadWS.subActividadWS.ObtenerSubActividadesDeUsuarioAsync(ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioRequest request) {
            return base.Channel.ObtenerSubActividadesDeUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioResponse> ObtenerSubActividadesDeUsuarioAsync(int idUsuario) {
            ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioRequest inValue = new ProyectoEscritorio.subActividadWS.ObtenerSubActividadesDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((ProyectoEscritorio.subActividadWS.subActividadWS)(this)).ObtenerSubActividadesDeUsuarioAsync(inValue);
        }
    }
}
