//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.ModificacionWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="ModificacionWS.ModificacionWS")]
    public interface ModificacionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/ObtenerModificacionesDeTableroRequest", ReplyAction="http://webservices/ModificacionWS/ObtenerModificacionesDeTableroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroResponse ObtenerModificacionesDeTablero(ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/ObtenerModificacionesDeTableroRequest", ReplyAction="http://webservices/ModificacionWS/ObtenerModificacionesDeTableroResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroResponse> ObtenerModificacionesDeTableroAsync(ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/CrearModificacionRequest", ReplyAction="http://webservices/ModificacionWS/CrearModificacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModificacionWS.CrearModificacionResponse CrearModificacion(ProyectoEscritorio.ModificacionWS.CrearModificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/CrearModificacionRequest", ReplyAction="http://webservices/ModificacionWS/CrearModificacionResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.CrearModificacionResponse> CrearModificacionAsync(ProyectoEscritorio.ModificacionWS.CrearModificacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/EliminarModificacionRequest", ReplyAction="http://webservices/ModificacionWS/EliminarModificacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModificacionWS.EliminarModificacionResponse EliminarModificacion(ProyectoEscritorio.ModificacionWS.EliminarModificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/EliminarModificacionRequest", ReplyAction="http://webservices/ModificacionWS/EliminarModificacionResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.EliminarModificacionResponse> EliminarModificacionAsync(ProyectoEscritorio.ModificacionWS.EliminarModificacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/SeleccionarModificacionRequest", ReplyAction="http://webservices/ModificacionWS/SeleccionarModificacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModificacionWS.SeleccionarModificacionResponse SeleccionarModificacion(ProyectoEscritorio.ModificacionWS.SeleccionarModificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/SeleccionarModificacionRequest", ReplyAction="http://webservices/ModificacionWS/SeleccionarModificacionResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.SeleccionarModificacionResponse> SeleccionarModificacionAsync(ProyectoEscritorio.ModificacionWS.SeleccionarModificacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/ObtenerModificacionesDeUsuarioRequest", ReplyAction="http://webservices/ModificacionWS/ObtenerModificacionesDeUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioResponse ObtenerModificacionesDeUsuario(ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModificacionWS/ObtenerModificacionesDeUsuarioRequest", ReplyAction="http://webservices/ModificacionWS/ObtenerModificacionesDeUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioResponse> ObtenerModificacionesDeUsuarioAsync(ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class modificacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string fechaField;
        
        private int idField;
        
        private int idTableroField;
        
        private int idUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTablero {
            get {
                return this.idTableroField;
            }
            set {
                this.idTableroField = value;
                this.RaisePropertyChanged("idTablero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerModificacionesDeTablero", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerModificacionesDeTableroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTablero;
        
        public ObtenerModificacionesDeTableroRequest() {
        }
        
        public ObtenerModificacionesDeTableroRequest(int idTablero) {
            this.idTablero = idTablero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerModificacionesDeTableroResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerModificacionesDeTableroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ModificacionWS.modificacion[] @return;
        
        public ObtenerModificacionesDeTableroResponse() {
        }
        
        public ObtenerModificacionesDeTableroResponse(ProyectoEscritorio.ModificacionWS.modificacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearModificacion", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class CrearModificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTablero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public CrearModificacionRequest() {
        }
        
        public CrearModificacionRequest(string descripcion, string fecha, int idTablero, int idUsuario) {
            this.descripcion = descripcion;
            this.fecha = fecha;
            this.idTablero = idTablero;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearModificacionResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class CrearModificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public CrearModificacionResponse() {
        }
        
        public CrearModificacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarModificacion", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarModificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarModificacionRequest() {
        }
        
        public EliminarModificacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarModificacionResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarModificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarModificacionResponse() {
        }
        
        public EliminarModificacionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarModificacion", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarModificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarModificacionRequest() {
        }
        
        public SeleccionarModificacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarModificacionResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarModificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ModificacionWS.modificacion @return;
        
        public SeleccionarModificacionResponse() {
        }
        
        public SeleccionarModificacionResponse(ProyectoEscritorio.ModificacionWS.modificacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerModificacionesDeUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerModificacionesDeUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public ObtenerModificacionesDeUsuarioRequest() {
        }
        
        public ObtenerModificacionesDeUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerModificacionesDeUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerModificacionesDeUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ModificacionWS.modificacion[] @return;
        
        public ObtenerModificacionesDeUsuarioResponse() {
        }
        
        public ObtenerModificacionesDeUsuarioResponse(ProyectoEscritorio.ModificacionWS.modificacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ModificacionWSChannel : ProyectoEscritorio.ModificacionWS.ModificacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModificacionWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.ModificacionWS.ModificacionWS>, ProyectoEscritorio.ModificacionWS.ModificacionWS {
        
        public ModificacionWSClient() {
        }
        
        public ModificacionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModificacionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModificacionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModificacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroResponse ProyectoEscritorio.ModificacionWS.ModificacionWS.ObtenerModificacionesDeTablero(ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroRequest request) {
            return base.Channel.ObtenerModificacionesDeTablero(request);
        }
        
        public ProyectoEscritorio.ModificacionWS.modificacion[] ObtenerModificacionesDeTablero(int idTablero) {
            ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroRequest inValue = new ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroRequest();
            inValue.idTablero = idTablero;
            ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroResponse retVal = ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).ObtenerModificacionesDeTablero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroResponse> ProyectoEscritorio.ModificacionWS.ModificacionWS.ObtenerModificacionesDeTableroAsync(ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroRequest request) {
            return base.Channel.ObtenerModificacionesDeTableroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroResponse> ObtenerModificacionesDeTableroAsync(int idTablero) {
            ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroRequest inValue = new ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeTableroRequest();
            inValue.idTablero = idTablero;
            return ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).ObtenerModificacionesDeTableroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModificacionWS.CrearModificacionResponse ProyectoEscritorio.ModificacionWS.ModificacionWS.CrearModificacion(ProyectoEscritorio.ModificacionWS.CrearModificacionRequest request) {
            return base.Channel.CrearModificacion(request);
        }
        
        public int CrearModificacion(string descripcion, string fecha, int idTablero, int idUsuario) {
            ProyectoEscritorio.ModificacionWS.CrearModificacionRequest inValue = new ProyectoEscritorio.ModificacionWS.CrearModificacionRequest();
            inValue.descripcion = descripcion;
            inValue.fecha = fecha;
            inValue.idTablero = idTablero;
            inValue.idUsuario = idUsuario;
            ProyectoEscritorio.ModificacionWS.CrearModificacionResponse retVal = ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).CrearModificacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.CrearModificacionResponse> ProyectoEscritorio.ModificacionWS.ModificacionWS.CrearModificacionAsync(ProyectoEscritorio.ModificacionWS.CrearModificacionRequest request) {
            return base.Channel.CrearModificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.CrearModificacionResponse> CrearModificacionAsync(string descripcion, string fecha, int idTablero, int idUsuario) {
            ProyectoEscritorio.ModificacionWS.CrearModificacionRequest inValue = new ProyectoEscritorio.ModificacionWS.CrearModificacionRequest();
            inValue.descripcion = descripcion;
            inValue.fecha = fecha;
            inValue.idTablero = idTablero;
            inValue.idUsuario = idUsuario;
            return ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).CrearModificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModificacionWS.EliminarModificacionResponse ProyectoEscritorio.ModificacionWS.ModificacionWS.EliminarModificacion(ProyectoEscritorio.ModificacionWS.EliminarModificacionRequest request) {
            return base.Channel.EliminarModificacion(request);
        }
        
        public bool EliminarModificacion(int id) {
            ProyectoEscritorio.ModificacionWS.EliminarModificacionRequest inValue = new ProyectoEscritorio.ModificacionWS.EliminarModificacionRequest();
            inValue.id = id;
            ProyectoEscritorio.ModificacionWS.EliminarModificacionResponse retVal = ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).EliminarModificacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.EliminarModificacionResponse> ProyectoEscritorio.ModificacionWS.ModificacionWS.EliminarModificacionAsync(ProyectoEscritorio.ModificacionWS.EliminarModificacionRequest request) {
            return base.Channel.EliminarModificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.EliminarModificacionResponse> EliminarModificacionAsync(int id) {
            ProyectoEscritorio.ModificacionWS.EliminarModificacionRequest inValue = new ProyectoEscritorio.ModificacionWS.EliminarModificacionRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).EliminarModificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModificacionWS.SeleccionarModificacionResponse ProyectoEscritorio.ModificacionWS.ModificacionWS.SeleccionarModificacion(ProyectoEscritorio.ModificacionWS.SeleccionarModificacionRequest request) {
            return base.Channel.SeleccionarModificacion(request);
        }
        
        public ProyectoEscritorio.ModificacionWS.modificacion SeleccionarModificacion(int id) {
            ProyectoEscritorio.ModificacionWS.SeleccionarModificacionRequest inValue = new ProyectoEscritorio.ModificacionWS.SeleccionarModificacionRequest();
            inValue.id = id;
            ProyectoEscritorio.ModificacionWS.SeleccionarModificacionResponse retVal = ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).SeleccionarModificacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.SeleccionarModificacionResponse> ProyectoEscritorio.ModificacionWS.ModificacionWS.SeleccionarModificacionAsync(ProyectoEscritorio.ModificacionWS.SeleccionarModificacionRequest request) {
            return base.Channel.SeleccionarModificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.SeleccionarModificacionResponse> SeleccionarModificacionAsync(int id) {
            ProyectoEscritorio.ModificacionWS.SeleccionarModificacionRequest inValue = new ProyectoEscritorio.ModificacionWS.SeleccionarModificacionRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).SeleccionarModificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioResponse ProyectoEscritorio.ModificacionWS.ModificacionWS.ObtenerModificacionesDeUsuario(ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioRequest request) {
            return base.Channel.ObtenerModificacionesDeUsuario(request);
        }
        
        public ProyectoEscritorio.ModificacionWS.modificacion[] ObtenerModificacionesDeUsuario(int idUsuario) {
            ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioRequest inValue = new ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioResponse retVal = ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).ObtenerModificacionesDeUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioResponse> ProyectoEscritorio.ModificacionWS.ModificacionWS.ObtenerModificacionesDeUsuarioAsync(ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioRequest request) {
            return base.Channel.ObtenerModificacionesDeUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioResponse> ObtenerModificacionesDeUsuarioAsync(int idUsuario) {
            ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioRequest inValue = new ProyectoEscritorio.ModificacionWS.ObtenerModificacionesDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((ProyectoEscritorio.ModificacionWS.ModificacionWS)(this)).ObtenerModificacionesDeUsuarioAsync(inValue);
        }
    }
}
