//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.ActividadWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="ActividadWS.ActividadWS")]
    public interface ActividadWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/AgregarActividadRequest", ReplyAction="http://webservices/ActividadWS/AgregarActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadWS.AgregarActividadResponse AgregarActividad(ProyectoEscritorio.ActividadWS.AgregarActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/AgregarActividadRequest", ReplyAction="http://webservices/ActividadWS/AgregarActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.AgregarActividadResponse> AgregarActividadAsync(ProyectoEscritorio.ActividadWS.AgregarActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/EditarActividadRequest", ReplyAction="http://webservices/ActividadWS/EditarActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadWS.EditarActividadResponse EditarActividad(ProyectoEscritorio.ActividadWS.EditarActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/EditarActividadRequest", ReplyAction="http://webservices/ActividadWS/EditarActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EditarActividadResponse> EditarActividadAsync(ProyectoEscritorio.ActividadWS.EditarActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/SeleccionarActividadRequest", ReplyAction="http://webservices/ActividadWS/SeleccionarActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadWS.SeleccionarActividadResponse SeleccionarActividad(ProyectoEscritorio.ActividadWS.SeleccionarActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/SeleccionarActividadRequest", ReplyAction="http://webservices/ActividadWS/SeleccionarActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.SeleccionarActividadResponse> SeleccionarActividadAsync(ProyectoEscritorio.ActividadWS.SeleccionarActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/EliminarActividadesRequest", ReplyAction="http://webservices/ActividadWS/EliminarActividadesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadWS.EliminarActividadesResponse EliminarActividades(ProyectoEscritorio.ActividadWS.EliminarActividadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/EliminarActividadesRequest", ReplyAction="http://webservices/ActividadWS/EliminarActividadesResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadesResponse> EliminarActividadesAsync(ProyectoEscritorio.ActividadWS.EliminarActividadesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/ObtenerActividadesDeModuloRequest", ReplyAction="http://webservices/ActividadWS/ObtenerActividadesDeModuloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloResponse ObtenerActividadesDeModulo(ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/ObtenerActividadesDeModuloRequest", ReplyAction="http://webservices/ActividadWS/ObtenerActividadesDeModuloResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloResponse> ObtenerActividadesDeModuloAsync(ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/EliminarActividadRequest", ReplyAction="http://webservices/ActividadWS/EliminarActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadWS.EliminarActividadResponse EliminarActividad(ProyectoEscritorio.ActividadWS.EliminarActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/EliminarActividadRequest", ReplyAction="http://webservices/ActividadWS/EliminarActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadResponse> EliminarActividadAsync(ProyectoEscritorio.ActividadWS.EliminarActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/EliminarActividadVirtualRequest", ReplyAction="http://webservices/ActividadWS/EliminarActividadVirtualResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadWS.EliminarActividadVirtualResponse EliminarActividadVirtual(ProyectoEscritorio.ActividadWS.EliminarActividadVirtualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadWS/EliminarActividadVirtualRequest", ReplyAction="http://webservices/ActividadWS/EliminarActividadVirtualResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadVirtualResponse> EliminarActividadVirtualAsync(ProyectoEscritorio.ActividadWS.EliminarActividadVirtualRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idModulo;
        
        public AgregarActividadRequest() {
        }
        
        public AgregarActividadRequest(string titulo, string descripcion, string vencimiento, string estado, int idModulo) {
            this.titulo = titulo;
            this.descripcion = descripcion;
            this.vencimiento = vencimiento;
            this.estado = estado;
            this.idModulo = idModulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public AgregarActividadResponse() {
        }
        
        public AgregarActividadResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public EditarActividadRequest() {
        }
        
        public EditarActividadRequest(int id, string titulo, string descripcion, string vencimiento, string estado) {
            this.id = id;
            this.titulo = titulo;
            this.descripcion = descripcion;
            this.vencimiento = vencimiento;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EditarActividadResponse() {
        }
        
        public EditarActividadResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class actividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string descripcionField;
        
        private string estadoField;
        
        private int idField;
        
        private int idModuloField;
        
        private string tituloField;
        
        private string vencimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
                this.RaisePropertyChanged("idModulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
                this.RaisePropertyChanged("vencimiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarActividadRequest() {
        }
        
        public SeleccionarActividadRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ActividadWS.actividad @return;
        
        public SeleccionarActividadResponse() {
        }
        
        public SeleccionarActividadResponse(ProyectoEscritorio.ActividadWS.actividad @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividades", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idModulo;
        
        public EliminarActividadesRequest() {
        }
        
        public EliminarActividadesRequest(int idModulo) {
            this.idModulo = idModulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividadesResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarActividadesResponse() {
        }
        
        public EliminarActividadesResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerActividadesDeModulo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerActividadesDeModuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idModulo;
        
        public ObtenerActividadesDeModuloRequest() {
        }
        
        public ObtenerActividadesDeModuloRequest(int idModulo) {
            this.idModulo = idModulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerActividadesDeModuloResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerActividadesDeModuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ActividadWS.actividad[] @return;
        
        public ObtenerActividadesDeModuloResponse() {
        }
        
        public ObtenerActividadesDeModuloResponse(ProyectoEscritorio.ActividadWS.actividad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarActividadRequest() {
        }
        
        public EliminarActividadRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarActividadResponse() {
        }
        
        public EliminarActividadResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividadVirtual", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadVirtualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarActividadVirtualRequest() {
        }
        
        public EliminarActividadVirtualRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividadVirtualResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadVirtualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarActividadVirtualResponse() {
        }
        
        public EliminarActividadVirtualResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActividadWSChannel : ProyectoEscritorio.ActividadWS.ActividadWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActividadWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.ActividadWS.ActividadWS>, ProyectoEscritorio.ActividadWS.ActividadWS {
        
        public ActividadWSClient() {
        }
        
        public ActividadWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActividadWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActividadWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActividadWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadWS.AgregarActividadResponse ProyectoEscritorio.ActividadWS.ActividadWS.AgregarActividad(ProyectoEscritorio.ActividadWS.AgregarActividadRequest request) {
            return base.Channel.AgregarActividad(request);
        }
        
        public int AgregarActividad(string titulo, string descripcion, string vencimiento, string estado, int idModulo) {
            ProyectoEscritorio.ActividadWS.AgregarActividadRequest inValue = new ProyectoEscritorio.ActividadWS.AgregarActividadRequest();
            inValue.titulo = titulo;
            inValue.descripcion = descripcion;
            inValue.vencimiento = vencimiento;
            inValue.estado = estado;
            inValue.idModulo = idModulo;
            ProyectoEscritorio.ActividadWS.AgregarActividadResponse retVal = ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).AgregarActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.AgregarActividadResponse> ProyectoEscritorio.ActividadWS.ActividadWS.AgregarActividadAsync(ProyectoEscritorio.ActividadWS.AgregarActividadRequest request) {
            return base.Channel.AgregarActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.AgregarActividadResponse> AgregarActividadAsync(string titulo, string descripcion, string vencimiento, string estado, int idModulo) {
            ProyectoEscritorio.ActividadWS.AgregarActividadRequest inValue = new ProyectoEscritorio.ActividadWS.AgregarActividadRequest();
            inValue.titulo = titulo;
            inValue.descripcion = descripcion;
            inValue.vencimiento = vencimiento;
            inValue.estado = estado;
            inValue.idModulo = idModulo;
            return ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).AgregarActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadWS.EditarActividadResponse ProyectoEscritorio.ActividadWS.ActividadWS.EditarActividad(ProyectoEscritorio.ActividadWS.EditarActividadRequest request) {
            return base.Channel.EditarActividad(request);
        }
        
        public bool EditarActividad(int id, string titulo, string descripcion, string vencimiento, string estado) {
            ProyectoEscritorio.ActividadWS.EditarActividadRequest inValue = new ProyectoEscritorio.ActividadWS.EditarActividadRequest();
            inValue.id = id;
            inValue.titulo = titulo;
            inValue.descripcion = descripcion;
            inValue.vencimiento = vencimiento;
            inValue.estado = estado;
            ProyectoEscritorio.ActividadWS.EditarActividadResponse retVal = ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).EditarActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EditarActividadResponse> ProyectoEscritorio.ActividadWS.ActividadWS.EditarActividadAsync(ProyectoEscritorio.ActividadWS.EditarActividadRequest request) {
            return base.Channel.EditarActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EditarActividadResponse> EditarActividadAsync(int id, string titulo, string descripcion, string vencimiento, string estado) {
            ProyectoEscritorio.ActividadWS.EditarActividadRequest inValue = new ProyectoEscritorio.ActividadWS.EditarActividadRequest();
            inValue.id = id;
            inValue.titulo = titulo;
            inValue.descripcion = descripcion;
            inValue.vencimiento = vencimiento;
            inValue.estado = estado;
            return ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).EditarActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadWS.SeleccionarActividadResponse ProyectoEscritorio.ActividadWS.ActividadWS.SeleccionarActividad(ProyectoEscritorio.ActividadWS.SeleccionarActividadRequest request) {
            return base.Channel.SeleccionarActividad(request);
        }
        
        public ProyectoEscritorio.ActividadWS.actividad SeleccionarActividad(int id) {
            ProyectoEscritorio.ActividadWS.SeleccionarActividadRequest inValue = new ProyectoEscritorio.ActividadWS.SeleccionarActividadRequest();
            inValue.id = id;
            ProyectoEscritorio.ActividadWS.SeleccionarActividadResponse retVal = ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).SeleccionarActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.SeleccionarActividadResponse> ProyectoEscritorio.ActividadWS.ActividadWS.SeleccionarActividadAsync(ProyectoEscritorio.ActividadWS.SeleccionarActividadRequest request) {
            return base.Channel.SeleccionarActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.SeleccionarActividadResponse> SeleccionarActividadAsync(int id) {
            ProyectoEscritorio.ActividadWS.SeleccionarActividadRequest inValue = new ProyectoEscritorio.ActividadWS.SeleccionarActividadRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).SeleccionarActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadWS.EliminarActividadesResponse ProyectoEscritorio.ActividadWS.ActividadWS.EliminarActividades(ProyectoEscritorio.ActividadWS.EliminarActividadesRequest request) {
            return base.Channel.EliminarActividades(request);
        }
        
        public bool EliminarActividades(int idModulo) {
            ProyectoEscritorio.ActividadWS.EliminarActividadesRequest inValue = new ProyectoEscritorio.ActividadWS.EliminarActividadesRequest();
            inValue.idModulo = idModulo;
            ProyectoEscritorio.ActividadWS.EliminarActividadesResponse retVal = ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).EliminarActividades(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadesResponse> ProyectoEscritorio.ActividadWS.ActividadWS.EliminarActividadesAsync(ProyectoEscritorio.ActividadWS.EliminarActividadesRequest request) {
            return base.Channel.EliminarActividadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadesResponse> EliminarActividadesAsync(int idModulo) {
            ProyectoEscritorio.ActividadWS.EliminarActividadesRequest inValue = new ProyectoEscritorio.ActividadWS.EliminarActividadesRequest();
            inValue.idModulo = idModulo;
            return ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).EliminarActividadesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloResponse ProyectoEscritorio.ActividadWS.ActividadWS.ObtenerActividadesDeModulo(ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloRequest request) {
            return base.Channel.ObtenerActividadesDeModulo(request);
        }
        
        public ProyectoEscritorio.ActividadWS.actividad[] ObtenerActividadesDeModulo(int idModulo) {
            ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloRequest inValue = new ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloRequest();
            inValue.idModulo = idModulo;
            ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloResponse retVal = ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).ObtenerActividadesDeModulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloResponse> ProyectoEscritorio.ActividadWS.ActividadWS.ObtenerActividadesDeModuloAsync(ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloRequest request) {
            return base.Channel.ObtenerActividadesDeModuloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloResponse> ObtenerActividadesDeModuloAsync(int idModulo) {
            ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloRequest inValue = new ProyectoEscritorio.ActividadWS.ObtenerActividadesDeModuloRequest();
            inValue.idModulo = idModulo;
            return ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).ObtenerActividadesDeModuloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadWS.EliminarActividadResponse ProyectoEscritorio.ActividadWS.ActividadWS.EliminarActividad(ProyectoEscritorio.ActividadWS.EliminarActividadRequest request) {
            return base.Channel.EliminarActividad(request);
        }
        
        public bool EliminarActividad(int id) {
            ProyectoEscritorio.ActividadWS.EliminarActividadRequest inValue = new ProyectoEscritorio.ActividadWS.EliminarActividadRequest();
            inValue.id = id;
            ProyectoEscritorio.ActividadWS.EliminarActividadResponse retVal = ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).EliminarActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadResponse> ProyectoEscritorio.ActividadWS.ActividadWS.EliminarActividadAsync(ProyectoEscritorio.ActividadWS.EliminarActividadRequest request) {
            return base.Channel.EliminarActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadResponse> EliminarActividadAsync(int id) {
            ProyectoEscritorio.ActividadWS.EliminarActividadRequest inValue = new ProyectoEscritorio.ActividadWS.EliminarActividadRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).EliminarActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadWS.EliminarActividadVirtualResponse ProyectoEscritorio.ActividadWS.ActividadWS.EliminarActividadVirtual(ProyectoEscritorio.ActividadWS.EliminarActividadVirtualRequest request) {
            return base.Channel.EliminarActividadVirtual(request);
        }
        
        public bool EliminarActividadVirtual(int id) {
            ProyectoEscritorio.ActividadWS.EliminarActividadVirtualRequest inValue = new ProyectoEscritorio.ActividadWS.EliminarActividadVirtualRequest();
            inValue.id = id;
            ProyectoEscritorio.ActividadWS.EliminarActividadVirtualResponse retVal = ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).EliminarActividadVirtual(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadVirtualResponse> ProyectoEscritorio.ActividadWS.ActividadWS.EliminarActividadVirtualAsync(ProyectoEscritorio.ActividadWS.EliminarActividadVirtualRequest request) {
            return base.Channel.EliminarActividadVirtualAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadWS.EliminarActividadVirtualResponse> EliminarActividadVirtualAsync(int id) {
            ProyectoEscritorio.ActividadWS.EliminarActividadVirtualRequest inValue = new ProyectoEscritorio.ActividadWS.EliminarActividadVirtualRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ActividadWS.ActividadWS)(this)).EliminarActividadVirtualAsync(inValue);
        }
    }
}
