//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.UsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="UsuarioWS.UsuarioWS")]
    public interface UsuarioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/AgregarUsuarioRequest", ReplyAction="http://webservices/UsuarioWS/AgregarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.UsuarioWS.AgregarUsuarioResponse AgregarUsuario(ProyectoEscritorio.UsuarioWS.AgregarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/AgregarUsuarioRequest", ReplyAction="http://webservices/UsuarioWS/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.AgregarUsuarioResponse> AgregarUsuarioAsync(ProyectoEscritorio.UsuarioWS.AgregarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/EditarUsuarioRequest", ReplyAction="http://webservices/UsuarioWS/EditarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.UsuarioWS.EditarUsuarioResponse EditarUsuario(ProyectoEscritorio.UsuarioWS.EditarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/EditarUsuarioRequest", ReplyAction="http://webservices/UsuarioWS/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.EditarUsuarioResponse> EditarUsuarioAsync(ProyectoEscritorio.UsuarioWS.EditarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/SeleccionarUsuarioRequest", ReplyAction="http://webservices/UsuarioWS/SeleccionarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioResponse SeleccionarUsuario(ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/SeleccionarUsuarioRequest", ReplyAction="http://webservices/UsuarioWS/SeleccionarUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioResponse> SeleccionarUsuarioAsync(ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/LoginRequest", ReplyAction="http://webservices/UsuarioWS/LoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.UsuarioWS.LoginResponse Login(ProyectoEscritorio.UsuarioWS.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/LoginRequest", ReplyAction="http://webservices/UsuarioWS/LoginResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.LoginResponse> LoginAsync(ProyectoEscritorio.UsuarioWS.LoginRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/SeleccionUsuarioPorEmailCoincidenciaRequest", ReplyAction="http://webservices/UsuarioWS/SeleccionUsuarioPorEmailCoincidenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaResponse SeleccionUsuarioPorEmailCoincidencia(ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/SeleccionUsuarioPorEmailCoincidenciaRequest", ReplyAction="http://webservices/UsuarioWS/SeleccionUsuarioPorEmailCoincidenciaResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaResponse> SeleccionUsuarioPorEmailCoincidenciaAsync(ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/SeleccionUsuarioPorEmailRequest", ReplyAction="http://webservices/UsuarioWS/SeleccionUsuarioPorEmailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailResponse SeleccionUsuarioPorEmail(ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/SeleccionUsuarioPorEmailRequest", ReplyAction="http://webservices/UsuarioWS/SeleccionUsuarioPorEmailResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailResponse> SeleccionUsuarioPorEmailAsync(ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/comprobarExistenciaEmailRequest", ReplyAction="http://webservices/UsuarioWS/comprobarExistenciaEmailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailResponse comprobarExistenciaEmail(ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/UsuarioWS/comprobarExistenciaEmailRequest", ReplyAction="http://webservices/UsuarioWS/comprobarExistenciaEmailResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailResponse> comprobarExistenciaEmailAsync(ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasena;
        
        public AgregarUsuarioRequest() {
        }
        
        public AgregarUsuarioRequest(string nombre, string email, string contrasena) {
            this.nombre = nombre;
            this.email = email;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public AgregarUsuarioResponse() {
        }
        
        public AgregarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasena;
        
        public EditarUsuarioRequest() {
        }
        
        public EditarUsuarioRequest(int id, string nombre, string email, string contrasena) {
            this.id = id;
            this.nombre = nombre;
            this.email = email;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EditarUsuarioResponse() {
        }
        
        public EditarUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contrasenaField;
        
        private string emailField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarUsuarioRequest() {
        }
        
        public SeleccionarUsuarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.UsuarioWS.usuario @return;
        
        public SeleccionarUsuarioResponse() {
        }
        
        public SeleccionarUsuarioResponse(ProyectoEscritorio.UsuarioWS.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contra;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string email, string contra) {
            this.email = email;
            this.contra = contra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.UsuarioWS.usuario @return;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ProyectoEscritorio.UsuarioWS.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionUsuarioPorEmailCoincidencia", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionUsuarioPorEmailCoincidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public SeleccionUsuarioPorEmailCoincidenciaRequest() {
        }
        
        public SeleccionUsuarioPorEmailCoincidenciaRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionUsuarioPorEmailCoincidenciaResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionUsuarioPorEmailCoincidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.UsuarioWS.usuario[] @return;
        
        public SeleccionUsuarioPorEmailCoincidenciaResponse() {
        }
        
        public SeleccionUsuarioPorEmailCoincidenciaResponse(ProyectoEscritorio.UsuarioWS.usuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionUsuarioPorEmail", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionUsuarioPorEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public SeleccionUsuarioPorEmailRequest() {
        }
        
        public SeleccionUsuarioPorEmailRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionUsuarioPorEmailResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionUsuarioPorEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public SeleccionUsuarioPorEmailResponse() {
        }
        
        public SeleccionUsuarioPorEmailResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobarExistenciaEmail", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class comprobarExistenciaEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        public comprobarExistenciaEmailRequest() {
        }
        
        public comprobarExistenciaEmailRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="comprobarExistenciaEmailResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class comprobarExistenciaEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public comprobarExistenciaEmailResponse() {
        }
        
        public comprobarExistenciaEmailResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioWSChannel : ProyectoEscritorio.UsuarioWS.UsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.UsuarioWS.UsuarioWS>, ProyectoEscritorio.UsuarioWS.UsuarioWS {
        
        public UsuarioWSClient() {
        }
        
        public UsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.UsuarioWS.AgregarUsuarioResponse ProyectoEscritorio.UsuarioWS.UsuarioWS.AgregarUsuario(ProyectoEscritorio.UsuarioWS.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuario(request);
        }
        
        public int AgregarUsuario(string nombre, string email, string contrasena) {
            ProyectoEscritorio.UsuarioWS.AgregarUsuarioRequest inValue = new ProyectoEscritorio.UsuarioWS.AgregarUsuarioRequest();
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.contrasena = contrasena;
            ProyectoEscritorio.UsuarioWS.AgregarUsuarioResponse retVal = ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).AgregarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.AgregarUsuarioResponse> ProyectoEscritorio.UsuarioWS.UsuarioWS.AgregarUsuarioAsync(ProyectoEscritorio.UsuarioWS.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.AgregarUsuarioResponse> AgregarUsuarioAsync(string nombre, string email, string contrasena) {
            ProyectoEscritorio.UsuarioWS.AgregarUsuarioRequest inValue = new ProyectoEscritorio.UsuarioWS.AgregarUsuarioRequest();
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.contrasena = contrasena;
            return ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).AgregarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.UsuarioWS.EditarUsuarioResponse ProyectoEscritorio.UsuarioWS.UsuarioWS.EditarUsuario(ProyectoEscritorio.UsuarioWS.EditarUsuarioRequest request) {
            return base.Channel.EditarUsuario(request);
        }
        
        public bool EditarUsuario(int id, string nombre, string email, string contrasena) {
            ProyectoEscritorio.UsuarioWS.EditarUsuarioRequest inValue = new ProyectoEscritorio.UsuarioWS.EditarUsuarioRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.contrasena = contrasena;
            ProyectoEscritorio.UsuarioWS.EditarUsuarioResponse retVal = ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).EditarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.EditarUsuarioResponse> ProyectoEscritorio.UsuarioWS.UsuarioWS.EditarUsuarioAsync(ProyectoEscritorio.UsuarioWS.EditarUsuarioRequest request) {
            return base.Channel.EditarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.EditarUsuarioResponse> EditarUsuarioAsync(int id, string nombre, string email, string contrasena) {
            ProyectoEscritorio.UsuarioWS.EditarUsuarioRequest inValue = new ProyectoEscritorio.UsuarioWS.EditarUsuarioRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.email = email;
            inValue.contrasena = contrasena;
            return ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).EditarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioResponse ProyectoEscritorio.UsuarioWS.UsuarioWS.SeleccionarUsuario(ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioRequest request) {
            return base.Channel.SeleccionarUsuario(request);
        }
        
        public ProyectoEscritorio.UsuarioWS.usuario SeleccionarUsuario(int id) {
            ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioRequest inValue = new ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioRequest();
            inValue.id = id;
            ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioResponse retVal = ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).SeleccionarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioResponse> ProyectoEscritorio.UsuarioWS.UsuarioWS.SeleccionarUsuarioAsync(ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioRequest request) {
            return base.Channel.SeleccionarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioResponse> SeleccionarUsuarioAsync(int id) {
            ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioRequest inValue = new ProyectoEscritorio.UsuarioWS.SeleccionarUsuarioRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).SeleccionarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.UsuarioWS.LoginResponse ProyectoEscritorio.UsuarioWS.UsuarioWS.Login(ProyectoEscritorio.UsuarioWS.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public ProyectoEscritorio.UsuarioWS.usuario Login(string email, string contra) {
            ProyectoEscritorio.UsuarioWS.LoginRequest inValue = new ProyectoEscritorio.UsuarioWS.LoginRequest();
            inValue.email = email;
            inValue.contra = contra;
            ProyectoEscritorio.UsuarioWS.LoginResponse retVal = ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).Login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.LoginResponse> ProyectoEscritorio.UsuarioWS.UsuarioWS.LoginAsync(ProyectoEscritorio.UsuarioWS.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.LoginResponse> LoginAsync(string email, string contra) {
            ProyectoEscritorio.UsuarioWS.LoginRequest inValue = new ProyectoEscritorio.UsuarioWS.LoginRequest();
            inValue.email = email;
            inValue.contra = contra;
            return ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaResponse ProyectoEscritorio.UsuarioWS.UsuarioWS.SeleccionUsuarioPorEmailCoincidencia(ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaRequest request) {
            return base.Channel.SeleccionUsuarioPorEmailCoincidencia(request);
        }
        
        public ProyectoEscritorio.UsuarioWS.usuario[] SeleccionUsuarioPorEmailCoincidencia(string email) {
            ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaRequest inValue = new ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaRequest();
            inValue.email = email;
            ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaResponse retVal = ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).SeleccionUsuarioPorEmailCoincidencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaResponse> ProyectoEscritorio.UsuarioWS.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaAsync(ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaRequest request) {
            return base.Channel.SeleccionUsuarioPorEmailCoincidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaResponse> SeleccionUsuarioPorEmailCoincidenciaAsync(string email) {
            ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaRequest inValue = new ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailCoincidenciaRequest();
            inValue.email = email;
            return ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).SeleccionUsuarioPorEmailCoincidenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailResponse ProyectoEscritorio.UsuarioWS.UsuarioWS.SeleccionUsuarioPorEmail(ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailRequest request) {
            return base.Channel.SeleccionUsuarioPorEmail(request);
        }
        
        public int SeleccionUsuarioPorEmail(string email) {
            ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailRequest inValue = new ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailRequest();
            inValue.email = email;
            ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailResponse retVal = ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).SeleccionUsuarioPorEmail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailResponse> ProyectoEscritorio.UsuarioWS.UsuarioWS.SeleccionUsuarioPorEmailAsync(ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailRequest request) {
            return base.Channel.SeleccionUsuarioPorEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailResponse> SeleccionUsuarioPorEmailAsync(string email) {
            ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailRequest inValue = new ProyectoEscritorio.UsuarioWS.SeleccionUsuarioPorEmailRequest();
            inValue.email = email;
            return ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).SeleccionUsuarioPorEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailResponse ProyectoEscritorio.UsuarioWS.UsuarioWS.comprobarExistenciaEmail(ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailRequest request) {
            return base.Channel.comprobarExistenciaEmail(request);
        }
        
        public bool comprobarExistenciaEmail(string email) {
            ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailRequest inValue = new ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailRequest();
            inValue.email = email;
            ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailResponse retVal = ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).comprobarExistenciaEmail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailResponse> ProyectoEscritorio.UsuarioWS.UsuarioWS.comprobarExistenciaEmailAsync(ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailRequest request) {
            return base.Channel.comprobarExistenciaEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailResponse> comprobarExistenciaEmailAsync(string email) {
            ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailRequest inValue = new ProyectoEscritorio.UsuarioWS.comprobarExistenciaEmailRequest();
            inValue.email = email;
            return ((ProyectoEscritorio.UsuarioWS.UsuarioWS)(this)).comprobarExistenciaEmailAsync(inValue);
        }
    }
}
