//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.tableroEquipoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="tableroEquipoWS.tableroEquipoWS")]
    public interface tableroEquipoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/CrearTableroEquipoRequest", ReplyAction="http://webservices/tableroEquipoWS/CrearTableroEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoResponse CrearTableroEquipo(ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/CrearTableroEquipoRequest", ReplyAction="http://webservices/tableroEquipoWS/CrearTableroEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoResponse> CrearTableroEquipoAsync(ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/EliminarTableroEquipoRequest", ReplyAction="http://webservices/tableroEquipoWS/EliminarTableroEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoResponse EliminarTableroEquipo(ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/EliminarTableroEquipoRequest", ReplyAction="http://webservices/tableroEquipoWS/EliminarTableroEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoResponse> EliminarTableroEquipoAsync(ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/EliminarTableroEquiposRequest", ReplyAction="http://webservices/tableroEquipoWS/EliminarTableroEquiposResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposResponse EliminarTableroEquipos(ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/EliminarTableroEquiposRequest", ReplyAction="http://webservices/tableroEquipoWS/EliminarTableroEquiposResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposResponse> EliminarTableroEquiposAsync(ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/SeleccionarTableroEquipoRequest", ReplyAction="http://webservices/tableroEquipoWS/SeleccionarTableroEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoResponse SeleccionarTableroEquipo(ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/SeleccionarTableroEquipoRequest", ReplyAction="http://webservices/tableroEquipoWS/SeleccionarTableroEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoResponse> SeleccionarTableroEquipoAsync(ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/ObtenerTablerosDeEquipoRequest", ReplyAction="http://webservices/tableroEquipoWS/ObtenerTablerosDeEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoResponse ObtenerTablerosDeEquipo(ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/ObtenerTablerosDeEquipoRequest", ReplyAction="http://webservices/tableroEquipoWS/ObtenerTablerosDeEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoResponse> ObtenerTablerosDeEquipoAsync(ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/ObtenerEquiposDeTableroRequest", ReplyAction="http://webservices/tableroEquipoWS/ObtenerEquiposDeTableroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroResponse ObtenerEquiposDeTablero(ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/tableroEquipoWS/ObtenerEquiposDeTableroRequest", ReplyAction="http://webservices/tableroEquipoWS/ObtenerEquiposDeTableroResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroResponse> ObtenerEquiposDeTableroAsync(ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearTableroEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class CrearTableroEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTablero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEquipo;
        
        public CrearTableroEquipoRequest() {
        }
        
        public CrearTableroEquipoRequest(int idTablero, int idEquipo) {
            this.idTablero = idTablero;
            this.idEquipo = idEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearTableroEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class CrearTableroEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public CrearTableroEquipoResponse() {
        }
        
        public CrearTableroEquipoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarTableroEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarTableroEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarTableroEquipoRequest() {
        }
        
        public EliminarTableroEquipoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarTableroEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarTableroEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarTableroEquipoResponse() {
        }
        
        public EliminarTableroEquipoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarTableroEquipos", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarTableroEquiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTablero;
        
        public EliminarTableroEquiposRequest() {
        }
        
        public EliminarTableroEquiposRequest(int idTablero) {
            this.idTablero = idTablero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarTableroEquiposResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarTableroEquiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarTableroEquiposResponse() {
        }
        
        public EliminarTableroEquiposResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class tableroEquipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int idEquipoField;
        
        private int idTableroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEquipo {
            get {
                return this.idEquipoField;
            }
            set {
                this.idEquipoField = value;
                this.RaisePropertyChanged("idEquipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTablero {
            get {
                return this.idTableroField;
            }
            set {
                this.idTableroField = value;
                this.RaisePropertyChanged("idTablero");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class equipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class tablero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarTableroEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarTableroEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarTableroEquipoRequest() {
        }
        
        public SeleccionarTableroEquipoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarTableroEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarTableroEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.tableroEquipoWS.tableroEquipo @return;
        
        public SeleccionarTableroEquipoResponse() {
        }
        
        public SeleccionarTableroEquipoResponse(ProyectoEscritorio.tableroEquipoWS.tableroEquipo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTablerosDeEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerTablerosDeEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEquipo;
        
        public ObtenerTablerosDeEquipoRequest() {
        }
        
        public ObtenerTablerosDeEquipoRequest(int idEquipo) {
            this.idEquipo = idEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTablerosDeEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerTablerosDeEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.tableroEquipoWS.tablero[] @return;
        
        public ObtenerTablerosDeEquipoResponse() {
        }
        
        public ObtenerTablerosDeEquipoResponse(ProyectoEscritorio.tableroEquipoWS.tablero[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerEquiposDeTablero", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerEquiposDeTableroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTablero;
        
        public ObtenerEquiposDeTableroRequest() {
        }
        
        public ObtenerEquiposDeTableroRequest(int idTablero) {
            this.idTablero = idTablero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerEquiposDeTableroResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerEquiposDeTableroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.tableroEquipoWS.equipo[] @return;
        
        public ObtenerEquiposDeTableroResponse() {
        }
        
        public ObtenerEquiposDeTableroResponse(ProyectoEscritorio.tableroEquipoWS.equipo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tableroEquipoWSChannel : ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tableroEquipoWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS>, ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS {
        
        public tableroEquipoWSClient() {
        }
        
        public tableroEquipoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tableroEquipoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tableroEquipoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tableroEquipoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoResponse ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.CrearTableroEquipo(ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoRequest request) {
            return base.Channel.CrearTableroEquipo(request);
        }
        
        public int CrearTableroEquipo(int idTablero, int idEquipo) {
            ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoRequest inValue = new ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoRequest();
            inValue.idTablero = idTablero;
            inValue.idEquipo = idEquipo;
            ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoResponse retVal = ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).CrearTableroEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoResponse> ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.CrearTableroEquipoAsync(ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoRequest request) {
            return base.Channel.CrearTableroEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoResponse> CrearTableroEquipoAsync(int idTablero, int idEquipo) {
            ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoRequest inValue = new ProyectoEscritorio.tableroEquipoWS.CrearTableroEquipoRequest();
            inValue.idTablero = idTablero;
            inValue.idEquipo = idEquipo;
            return ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).CrearTableroEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoResponse ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.EliminarTableroEquipo(ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoRequest request) {
            return base.Channel.EliminarTableroEquipo(request);
        }
        
        public bool EliminarTableroEquipo(int id) {
            ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoRequest inValue = new ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoRequest();
            inValue.id = id;
            ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoResponse retVal = ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).EliminarTableroEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoResponse> ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.EliminarTableroEquipoAsync(ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoRequest request) {
            return base.Channel.EliminarTableroEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoResponse> EliminarTableroEquipoAsync(int id) {
            ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoRequest inValue = new ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquipoRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).EliminarTableroEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposResponse ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.EliminarTableroEquipos(ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposRequest request) {
            return base.Channel.EliminarTableroEquipos(request);
        }
        
        public bool EliminarTableroEquipos(int idTablero) {
            ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposRequest inValue = new ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposRequest();
            inValue.idTablero = idTablero;
            ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposResponse retVal = ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).EliminarTableroEquipos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposResponse> ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.EliminarTableroEquiposAsync(ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposRequest request) {
            return base.Channel.EliminarTableroEquiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposResponse> EliminarTableroEquiposAsync(int idTablero) {
            ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposRequest inValue = new ProyectoEscritorio.tableroEquipoWS.EliminarTableroEquiposRequest();
            inValue.idTablero = idTablero;
            return ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).EliminarTableroEquiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoResponse ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.SeleccionarTableroEquipo(ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoRequest request) {
            return base.Channel.SeleccionarTableroEquipo(request);
        }
        
        public ProyectoEscritorio.tableroEquipoWS.tableroEquipo SeleccionarTableroEquipo(int id) {
            ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoRequest inValue = new ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoRequest();
            inValue.id = id;
            ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoResponse retVal = ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).SeleccionarTableroEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoResponse> ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.SeleccionarTableroEquipoAsync(ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoRequest request) {
            return base.Channel.SeleccionarTableroEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoResponse> SeleccionarTableroEquipoAsync(int id) {
            ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoRequest inValue = new ProyectoEscritorio.tableroEquipoWS.SeleccionarTableroEquipoRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).SeleccionarTableroEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoResponse ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.ObtenerTablerosDeEquipo(ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoRequest request) {
            return base.Channel.ObtenerTablerosDeEquipo(request);
        }
        
        public ProyectoEscritorio.tableroEquipoWS.tablero[] ObtenerTablerosDeEquipo(int idEquipo) {
            ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoRequest inValue = new ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoRequest();
            inValue.idEquipo = idEquipo;
            ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoResponse retVal = ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).ObtenerTablerosDeEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoResponse> ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.ObtenerTablerosDeEquipoAsync(ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoRequest request) {
            return base.Channel.ObtenerTablerosDeEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoResponse> ObtenerTablerosDeEquipoAsync(int idEquipo) {
            ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoRequest inValue = new ProyectoEscritorio.tableroEquipoWS.ObtenerTablerosDeEquipoRequest();
            inValue.idEquipo = idEquipo;
            return ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).ObtenerTablerosDeEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroResponse ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.ObtenerEquiposDeTablero(ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroRequest request) {
            return base.Channel.ObtenerEquiposDeTablero(request);
        }
        
        public ProyectoEscritorio.tableroEquipoWS.equipo[] ObtenerEquiposDeTablero(int idTablero) {
            ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroRequest inValue = new ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroRequest();
            inValue.idTablero = idTablero;
            ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroResponse retVal = ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).ObtenerEquiposDeTablero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroResponse> ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS.ObtenerEquiposDeTableroAsync(ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroRequest request) {
            return base.Channel.ObtenerEquiposDeTableroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroResponse> ObtenerEquiposDeTableroAsync(int idTablero) {
            ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroRequest inValue = new ProyectoEscritorio.tableroEquipoWS.ObtenerEquiposDeTableroRequest();
            inValue.idTablero = idTablero;
            return ((ProyectoEscritorio.tableroEquipoWS.tableroEquipoWS)(this)).ObtenerEquiposDeTableroAsync(inValue);
        }
    }
}
