//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.EquipoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="EquipoWS.EquipoWS")]
    public interface EquipoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoWS/AgregarEquipoRequest", ReplyAction="http://webservices/EquipoWS/AgregarEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoWS.AgregarEquipoResponse AgregarEquipo(ProyectoEscritorio.EquipoWS.AgregarEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoWS/AgregarEquipoRequest", ReplyAction="http://webservices/EquipoWS/AgregarEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.AgregarEquipoResponse> AgregarEquipoAsync(ProyectoEscritorio.EquipoWS.AgregarEquipoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoWS/EliminarEquipoRequest", ReplyAction="http://webservices/EquipoWS/EliminarEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoWS.EliminarEquipoResponse EliminarEquipo(ProyectoEscritorio.EquipoWS.EliminarEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoWS/EliminarEquipoRequest", ReplyAction="http://webservices/EquipoWS/EliminarEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.EliminarEquipoResponse> EliminarEquipoAsync(ProyectoEscritorio.EquipoWS.EliminarEquipoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoWS/EditarEquipoRequest", ReplyAction="http://webservices/EquipoWS/EditarEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoWS.EditarEquipoResponse EditarEquipo(ProyectoEscritorio.EquipoWS.EditarEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoWS/EditarEquipoRequest", ReplyAction="http://webservices/EquipoWS/EditarEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.EditarEquipoResponse> EditarEquipoAsync(ProyectoEscritorio.EquipoWS.EditarEquipoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoWS/SeleccionarEquipoRequest", ReplyAction="http://webservices/EquipoWS/SeleccionarEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoWS.SeleccionarEquipoResponse SeleccionarEquipo(ProyectoEscritorio.EquipoWS.SeleccionarEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoWS/SeleccionarEquipoRequest", ReplyAction="http://webservices/EquipoWS/SeleccionarEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.SeleccionarEquipoResponse> SeleccionarEquipoAsync(ProyectoEscritorio.EquipoWS.SeleccionarEquipoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        public AgregarEquipoRequest() {
        }
        
        public AgregarEquipoRequest(string nombre, string descripcion) {
            this.nombre = nombre;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public AgregarEquipoResponse() {
        }
        
        public AgregarEquipoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarEquipoRequest() {
        }
        
        public EliminarEquipoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarEquipoResponse() {
        }
        
        public EliminarEquipoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        public EditarEquipoRequest() {
        }
        
        public EditarEquipoRequest(int id, string nombre, string descripcion) {
            this.id = id;
            this.nombre = nombre;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EditarEquipoResponse() {
        }
        
        public EditarEquipoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class equipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarEquipoRequest() {
        }
        
        public SeleccionarEquipoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.EquipoWS.equipo @return;
        
        public SeleccionarEquipoResponse() {
        }
        
        public SeleccionarEquipoResponse(ProyectoEscritorio.EquipoWS.equipo @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EquipoWSChannel : ProyectoEscritorio.EquipoWS.EquipoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquipoWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.EquipoWS.EquipoWS>, ProyectoEscritorio.EquipoWS.EquipoWS {
        
        public EquipoWSClient() {
        }
        
        public EquipoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquipoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoWS.AgregarEquipoResponse ProyectoEscritorio.EquipoWS.EquipoWS.AgregarEquipo(ProyectoEscritorio.EquipoWS.AgregarEquipoRequest request) {
            return base.Channel.AgregarEquipo(request);
        }
        
        public int AgregarEquipo(string nombre, string descripcion) {
            ProyectoEscritorio.EquipoWS.AgregarEquipoRequest inValue = new ProyectoEscritorio.EquipoWS.AgregarEquipoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            ProyectoEscritorio.EquipoWS.AgregarEquipoResponse retVal = ((ProyectoEscritorio.EquipoWS.EquipoWS)(this)).AgregarEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.AgregarEquipoResponse> ProyectoEscritorio.EquipoWS.EquipoWS.AgregarEquipoAsync(ProyectoEscritorio.EquipoWS.AgregarEquipoRequest request) {
            return base.Channel.AgregarEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.AgregarEquipoResponse> AgregarEquipoAsync(string nombre, string descripcion) {
            ProyectoEscritorio.EquipoWS.AgregarEquipoRequest inValue = new ProyectoEscritorio.EquipoWS.AgregarEquipoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            return ((ProyectoEscritorio.EquipoWS.EquipoWS)(this)).AgregarEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoWS.EliminarEquipoResponse ProyectoEscritorio.EquipoWS.EquipoWS.EliminarEquipo(ProyectoEscritorio.EquipoWS.EliminarEquipoRequest request) {
            return base.Channel.EliminarEquipo(request);
        }
        
        public bool EliminarEquipo(int id) {
            ProyectoEscritorio.EquipoWS.EliminarEquipoRequest inValue = new ProyectoEscritorio.EquipoWS.EliminarEquipoRequest();
            inValue.id = id;
            ProyectoEscritorio.EquipoWS.EliminarEquipoResponse retVal = ((ProyectoEscritorio.EquipoWS.EquipoWS)(this)).EliminarEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.EliminarEquipoResponse> ProyectoEscritorio.EquipoWS.EquipoWS.EliminarEquipoAsync(ProyectoEscritorio.EquipoWS.EliminarEquipoRequest request) {
            return base.Channel.EliminarEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.EliminarEquipoResponse> EliminarEquipoAsync(int id) {
            ProyectoEscritorio.EquipoWS.EliminarEquipoRequest inValue = new ProyectoEscritorio.EquipoWS.EliminarEquipoRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.EquipoWS.EquipoWS)(this)).EliminarEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoWS.EditarEquipoResponse ProyectoEscritorio.EquipoWS.EquipoWS.EditarEquipo(ProyectoEscritorio.EquipoWS.EditarEquipoRequest request) {
            return base.Channel.EditarEquipo(request);
        }
        
        public bool EditarEquipo(int id, string nombre, string descripcion) {
            ProyectoEscritorio.EquipoWS.EditarEquipoRequest inValue = new ProyectoEscritorio.EquipoWS.EditarEquipoRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            ProyectoEscritorio.EquipoWS.EditarEquipoResponse retVal = ((ProyectoEscritorio.EquipoWS.EquipoWS)(this)).EditarEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.EditarEquipoResponse> ProyectoEscritorio.EquipoWS.EquipoWS.EditarEquipoAsync(ProyectoEscritorio.EquipoWS.EditarEquipoRequest request) {
            return base.Channel.EditarEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.EditarEquipoResponse> EditarEquipoAsync(int id, string nombre, string descripcion) {
            ProyectoEscritorio.EquipoWS.EditarEquipoRequest inValue = new ProyectoEscritorio.EquipoWS.EditarEquipoRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            return ((ProyectoEscritorio.EquipoWS.EquipoWS)(this)).EditarEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoWS.SeleccionarEquipoResponse ProyectoEscritorio.EquipoWS.EquipoWS.SeleccionarEquipo(ProyectoEscritorio.EquipoWS.SeleccionarEquipoRequest request) {
            return base.Channel.SeleccionarEquipo(request);
        }
        
        public ProyectoEscritorio.EquipoWS.equipo SeleccionarEquipo(int id) {
            ProyectoEscritorio.EquipoWS.SeleccionarEquipoRequest inValue = new ProyectoEscritorio.EquipoWS.SeleccionarEquipoRequest();
            inValue.id = id;
            ProyectoEscritorio.EquipoWS.SeleccionarEquipoResponse retVal = ((ProyectoEscritorio.EquipoWS.EquipoWS)(this)).SeleccionarEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.SeleccionarEquipoResponse> ProyectoEscritorio.EquipoWS.EquipoWS.SeleccionarEquipoAsync(ProyectoEscritorio.EquipoWS.SeleccionarEquipoRequest request) {
            return base.Channel.SeleccionarEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoWS.SeleccionarEquipoResponse> SeleccionarEquipoAsync(int id) {
            ProyectoEscritorio.EquipoWS.SeleccionarEquipoRequest inValue = new ProyectoEscritorio.EquipoWS.SeleccionarEquipoRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.EquipoWS.EquipoWS)(this)).SeleccionarEquipoAsync(inValue);
        }
    }
}
