//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.ActividadUsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="ActividadUsuarioWS.ActividadUsuarioWS")]
    public interface ActividadUsuarioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/AgregarActividadUsuarioRequest", ReplyAction="http://webservices/ActividadUsuarioWS/AgregarActividadUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioResponse AgregarActividadUsuario(ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/AgregarActividadUsuarioRequest", ReplyAction="http://webservices/ActividadUsuarioWS/AgregarActividadUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioResponse> AgregarActividadUsuarioAsync(ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/EliminarActividadUsuarioRequest", ReplyAction="http://webservices/ActividadUsuarioWS/EliminarActividadUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioResponse EliminarActividadUsuario(ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/EliminarActividadUsuarioRequest", ReplyAction="http://webservices/ActividadUsuarioWS/EliminarActividadUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioResponse> EliminarActividadUsuarioAsync(ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/EliminarActividadUsuariosRequest", ReplyAction="http://webservices/ActividadUsuarioWS/EliminarActividadUsuariosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosResponse EliminarActividadUsuarios(ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/EliminarActividadUsuariosRequest", ReplyAction="http://webservices/ActividadUsuarioWS/EliminarActividadUsuariosResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosResponse> EliminarActividadUsuariosAsync(ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/SeleccionarActividadUsuarioRequest", ReplyAction="http://webservices/ActividadUsuarioWS/SeleccionarActividadUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioResponse SeleccionarActividadUsuario(ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/SeleccionarActividadUsuarioRequest", ReplyAction="http://webservices/ActividadUsuarioWS/SeleccionarActividadUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioResponse> SeleccionarActividadUsuarioAsync(ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/ObtenerActividadesDeUsuarioRequest", ReplyAction="http://webservices/ActividadUsuarioWS/ObtenerActividadesDeUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioResponse ObtenerActividadesDeUsuario(ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/ObtenerActividadesDeUsuarioRequest", ReplyAction="http://webservices/ActividadUsuarioWS/ObtenerActividadesDeUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioResponse> ObtenerActividadesDeUsuarioAsync(ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/ObtenerUsuariosDeActividadRequest", ReplyAction="http://webservices/ActividadUsuarioWS/ObtenerUsuariosDeActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadResponse ObtenerUsuariosDeActividad(ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ActividadUsuarioWS/ObtenerUsuariosDeActividadRequest", ReplyAction="http://webservices/ActividadUsuarioWS/ObtenerUsuariosDeActividadResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadResponse> ObtenerUsuariosDeActividadAsync(ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarActividadUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarActividadUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idActividad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public AgregarActividadUsuarioRequest() {
        }
        
        public AgregarActividadUsuarioRequest(int idActividad, int idUsuario) {
            this.idActividad = idActividad;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarActividadUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarActividadUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public AgregarActividadUsuarioResponse() {
        }
        
        public AgregarActividadUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividadUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarActividadUsuarioRequest() {
        }
        
        public EliminarActividadUsuarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividadUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarActividadUsuarioResponse() {
        }
        
        public EliminarActividadUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividadUsuarios", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idActvidad;
        
        public EliminarActividadUsuariosRequest() {
        }
        
        public EliminarActividadUsuariosRequest(int idActvidad) {
            this.idActvidad = idActvidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarActividadUsuariosResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarActividadUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarActividadUsuariosResponse() {
        }
        
        public EliminarActividadUsuariosResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class actividadUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int idActividadField;
        
        private int idUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
                this.RaisePropertyChanged("idActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contrasenaField;
        
        private string emailField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class actividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private string descripcionField;
        
        private string estadoField;
        
        private int idField;
        
        private int idModuloField;
        
        private string tituloField;
        
        private string vencimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
                this.RaisePropertyChanged("idModulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
                this.RaisePropertyChanged("vencimiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarActividadUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarActividadUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarActividadUsuarioRequest() {
        }
        
        public SeleccionarActividadUsuarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarActividadUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarActividadUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ActividadUsuarioWS.actividadUsuario @return;
        
        public SeleccionarActividadUsuarioResponse() {
        }
        
        public SeleccionarActividadUsuarioResponse(ProyectoEscritorio.ActividadUsuarioWS.actividadUsuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerActividadesDeUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerActividadesDeUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public ObtenerActividadesDeUsuarioRequest() {
        }
        
        public ObtenerActividadesDeUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerActividadesDeUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerActividadesDeUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ActividadUsuarioWS.actividad[] @return;
        
        public ObtenerActividadesDeUsuarioResponse() {
        }
        
        public ObtenerActividadesDeUsuarioResponse(ProyectoEscritorio.ActividadUsuarioWS.actividad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuariosDeActividad", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerUsuariosDeActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idActividad;
        
        public ObtenerUsuariosDeActividadRequest() {
        }
        
        public ObtenerUsuariosDeActividadRequest(int idActividad) {
            this.idActividad = idActividad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuariosDeActividadResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerUsuariosDeActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ActividadUsuarioWS.usuario[] @return;
        
        public ObtenerUsuariosDeActividadResponse() {
        }
        
        public ObtenerUsuariosDeActividadResponse(ProyectoEscritorio.ActividadUsuarioWS.usuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActividadUsuarioWSChannel : ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActividadUsuarioWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS>, ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS {
        
        public ActividadUsuarioWSClient() {
        }
        
        public ActividadUsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActividadUsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActividadUsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActividadUsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioResponse ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.AgregarActividadUsuario(ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioRequest request) {
            return base.Channel.AgregarActividadUsuario(request);
        }
        
        public int AgregarActividadUsuario(int idActividad, int idUsuario) {
            ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioRequest();
            inValue.idActividad = idActividad;
            inValue.idUsuario = idUsuario;
            ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioResponse retVal = ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).AgregarActividadUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioResponse> ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.AgregarActividadUsuarioAsync(ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioRequest request) {
            return base.Channel.AgregarActividadUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioResponse> AgregarActividadUsuarioAsync(int idActividad, int idUsuario) {
            ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.AgregarActividadUsuarioRequest();
            inValue.idActividad = idActividad;
            inValue.idUsuario = idUsuario;
            return ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).AgregarActividadUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioResponse ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.EliminarActividadUsuario(ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioRequest request) {
            return base.Channel.EliminarActividadUsuario(request);
        }
        
        public bool EliminarActividadUsuario(int id) {
            ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioRequest();
            inValue.id = id;
            ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioResponse retVal = ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).EliminarActividadUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioResponse> ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.EliminarActividadUsuarioAsync(ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioRequest request) {
            return base.Channel.EliminarActividadUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioResponse> EliminarActividadUsuarioAsync(int id) {
            ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuarioRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).EliminarActividadUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosResponse ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.EliminarActividadUsuarios(ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosRequest request) {
            return base.Channel.EliminarActividadUsuarios(request);
        }
        
        public bool EliminarActividadUsuarios(int idActvidad) {
            ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosRequest();
            inValue.idActvidad = idActvidad;
            ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosResponse retVal = ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).EliminarActividadUsuarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosResponse> ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.EliminarActividadUsuariosAsync(ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosRequest request) {
            return base.Channel.EliminarActividadUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosResponse> EliminarActividadUsuariosAsync(int idActvidad) {
            ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.EliminarActividadUsuariosRequest();
            inValue.idActvidad = idActvidad;
            return ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).EliminarActividadUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioResponse ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.SeleccionarActividadUsuario(ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioRequest request) {
            return base.Channel.SeleccionarActividadUsuario(request);
        }
        
        public ProyectoEscritorio.ActividadUsuarioWS.actividadUsuario SeleccionarActividadUsuario(int id) {
            ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioRequest();
            inValue.id = id;
            ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioResponse retVal = ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).SeleccionarActividadUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioResponse> ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.SeleccionarActividadUsuarioAsync(ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioRequest request) {
            return base.Channel.SeleccionarActividadUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioResponse> SeleccionarActividadUsuarioAsync(int id) {
            ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.SeleccionarActividadUsuarioRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).SeleccionarActividadUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioResponse ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.ObtenerActividadesDeUsuario(ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioRequest request) {
            return base.Channel.ObtenerActividadesDeUsuario(request);
        }
        
        public ProyectoEscritorio.ActividadUsuarioWS.actividad[] ObtenerActividadesDeUsuario(int idUsuario) {
            ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioResponse retVal = ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).ObtenerActividadesDeUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioResponse> ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.ObtenerActividadesDeUsuarioAsync(ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioRequest request) {
            return base.Channel.ObtenerActividadesDeUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioResponse> ObtenerActividadesDeUsuarioAsync(int idUsuario) {
            ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.ObtenerActividadesDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).ObtenerActividadesDeUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadResponse ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.ObtenerUsuariosDeActividad(ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadRequest request) {
            return base.Channel.ObtenerUsuariosDeActividad(request);
        }
        
        public ProyectoEscritorio.ActividadUsuarioWS.usuario[] ObtenerUsuariosDeActividad(int idActividad) {
            ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadRequest();
            inValue.idActividad = idActividad;
            ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadResponse retVal = ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).ObtenerUsuariosDeActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadResponse> ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS.ObtenerUsuariosDeActividadAsync(ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadRequest request) {
            return base.Channel.ObtenerUsuariosDeActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadResponse> ObtenerUsuariosDeActividadAsync(int idActividad) {
            ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadRequest inValue = new ProyectoEscritorio.ActividadUsuarioWS.ObtenerUsuariosDeActividadRequest();
            inValue.idActividad = idActividad;
            return ((ProyectoEscritorio.ActividadUsuarioWS.ActividadUsuarioWS)(this)).ObtenerUsuariosDeActividadAsync(inValue);
        }
    }
}
