//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.TableroWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="TableroWS.TableroWS")]
    public interface TableroWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/TableroWS/AgregarTableroRequest", ReplyAction="http://webservices/TableroWS/AgregarTableroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.TableroWS.AgregarTableroResponse AgregarTablero(ProyectoEscritorio.TableroWS.AgregarTableroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/TableroWS/AgregarTableroRequest", ReplyAction="http://webservices/TableroWS/AgregarTableroResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.AgregarTableroResponse> AgregarTableroAsync(ProyectoEscritorio.TableroWS.AgregarTableroRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/TableroWS/EliminarTableroRequest", ReplyAction="http://webservices/TableroWS/EliminarTableroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.TableroWS.EliminarTableroResponse EliminarTablero(ProyectoEscritorio.TableroWS.EliminarTableroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/TableroWS/EliminarTableroRequest", ReplyAction="http://webservices/TableroWS/EliminarTableroResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.EliminarTableroResponse> EliminarTableroAsync(ProyectoEscritorio.TableroWS.EliminarTableroRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/TableroWS/EditarTableroRequest", ReplyAction="http://webservices/TableroWS/EditarTableroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.TableroWS.EditarTableroResponse EditarTablero(ProyectoEscritorio.TableroWS.EditarTableroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/TableroWS/EditarTableroRequest", ReplyAction="http://webservices/TableroWS/EditarTableroResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.EditarTableroResponse> EditarTableroAsync(ProyectoEscritorio.TableroWS.EditarTableroRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/TableroWS/SeleccionarTableroRequest", ReplyAction="http://webservices/TableroWS/SeleccionarTableroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.TableroWS.SeleccionarTableroResponse SeleccionarTablero(ProyectoEscritorio.TableroWS.SeleccionarTableroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/TableroWS/SeleccionarTableroRequest", ReplyAction="http://webservices/TableroWS/SeleccionarTableroResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.SeleccionarTableroResponse> SeleccionarTableroAsync(ProyectoEscritorio.TableroWS.SeleccionarTableroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarTablero", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarTableroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titulo;
        
        public AgregarTableroRequest() {
        }
        
        public AgregarTableroRequest(string titulo) {
            this.titulo = titulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarTableroResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarTableroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public AgregarTableroResponse() {
        }
        
        public AgregarTableroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarTablero", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarTableroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarTableroRequest() {
        }
        
        public EliminarTableroRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarTableroResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarTableroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarTableroResponse() {
        }
        
        public EliminarTableroResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarTablero", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarTableroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titulo;
        
        public EditarTableroRequest() {
        }
        
        public EditarTableroRequest(int id, string titulo) {
            this.id = id;
            this.titulo = titulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarTableroResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarTableroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EditarTableroResponse() {
        }
        
        public EditarTableroResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class tablero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarTablero", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarTableroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarTableroRequest() {
        }
        
        public SeleccionarTableroRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarTableroResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarTableroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.TableroWS.tablero @return;
        
        public SeleccionarTableroResponse() {
        }
        
        public SeleccionarTableroResponse(ProyectoEscritorio.TableroWS.tablero @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TableroWSChannel : ProyectoEscritorio.TableroWS.TableroWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TableroWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.TableroWS.TableroWS>, ProyectoEscritorio.TableroWS.TableroWS {
        
        public TableroWSClient() {
        }
        
        public TableroWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TableroWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TableroWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TableroWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.TableroWS.AgregarTableroResponse ProyectoEscritorio.TableroWS.TableroWS.AgregarTablero(ProyectoEscritorio.TableroWS.AgregarTableroRequest request) {
            return base.Channel.AgregarTablero(request);
        }
        
        public int AgregarTablero(string titulo) {
            ProyectoEscritorio.TableroWS.AgregarTableroRequest inValue = new ProyectoEscritorio.TableroWS.AgregarTableroRequest();
            inValue.titulo = titulo;
            ProyectoEscritorio.TableroWS.AgregarTableroResponse retVal = ((ProyectoEscritorio.TableroWS.TableroWS)(this)).AgregarTablero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.AgregarTableroResponse> ProyectoEscritorio.TableroWS.TableroWS.AgregarTableroAsync(ProyectoEscritorio.TableroWS.AgregarTableroRequest request) {
            return base.Channel.AgregarTableroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.AgregarTableroResponse> AgregarTableroAsync(string titulo) {
            ProyectoEscritorio.TableroWS.AgregarTableroRequest inValue = new ProyectoEscritorio.TableroWS.AgregarTableroRequest();
            inValue.titulo = titulo;
            return ((ProyectoEscritorio.TableroWS.TableroWS)(this)).AgregarTableroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.TableroWS.EliminarTableroResponse ProyectoEscritorio.TableroWS.TableroWS.EliminarTablero(ProyectoEscritorio.TableroWS.EliminarTableroRequest request) {
            return base.Channel.EliminarTablero(request);
        }
        
        public bool EliminarTablero(int id) {
            ProyectoEscritorio.TableroWS.EliminarTableroRequest inValue = new ProyectoEscritorio.TableroWS.EliminarTableroRequest();
            inValue.id = id;
            ProyectoEscritorio.TableroWS.EliminarTableroResponse retVal = ((ProyectoEscritorio.TableroWS.TableroWS)(this)).EliminarTablero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.EliminarTableroResponse> ProyectoEscritorio.TableroWS.TableroWS.EliminarTableroAsync(ProyectoEscritorio.TableroWS.EliminarTableroRequest request) {
            return base.Channel.EliminarTableroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.EliminarTableroResponse> EliminarTableroAsync(int id) {
            ProyectoEscritorio.TableroWS.EliminarTableroRequest inValue = new ProyectoEscritorio.TableroWS.EliminarTableroRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.TableroWS.TableroWS)(this)).EliminarTableroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.TableroWS.EditarTableroResponse ProyectoEscritorio.TableroWS.TableroWS.EditarTablero(ProyectoEscritorio.TableroWS.EditarTableroRequest request) {
            return base.Channel.EditarTablero(request);
        }
        
        public bool EditarTablero(int id, string titulo) {
            ProyectoEscritorio.TableroWS.EditarTableroRequest inValue = new ProyectoEscritorio.TableroWS.EditarTableroRequest();
            inValue.id = id;
            inValue.titulo = titulo;
            ProyectoEscritorio.TableroWS.EditarTableroResponse retVal = ((ProyectoEscritorio.TableroWS.TableroWS)(this)).EditarTablero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.EditarTableroResponse> ProyectoEscritorio.TableroWS.TableroWS.EditarTableroAsync(ProyectoEscritorio.TableroWS.EditarTableroRequest request) {
            return base.Channel.EditarTableroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.EditarTableroResponse> EditarTableroAsync(int id, string titulo) {
            ProyectoEscritorio.TableroWS.EditarTableroRequest inValue = new ProyectoEscritorio.TableroWS.EditarTableroRequest();
            inValue.id = id;
            inValue.titulo = titulo;
            return ((ProyectoEscritorio.TableroWS.TableroWS)(this)).EditarTableroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.TableroWS.SeleccionarTableroResponse ProyectoEscritorio.TableroWS.TableroWS.SeleccionarTablero(ProyectoEscritorio.TableroWS.SeleccionarTableroRequest request) {
            return base.Channel.SeleccionarTablero(request);
        }
        
        public ProyectoEscritorio.TableroWS.tablero SeleccionarTablero(int id) {
            ProyectoEscritorio.TableroWS.SeleccionarTableroRequest inValue = new ProyectoEscritorio.TableroWS.SeleccionarTableroRequest();
            inValue.id = id;
            ProyectoEscritorio.TableroWS.SeleccionarTableroResponse retVal = ((ProyectoEscritorio.TableroWS.TableroWS)(this)).SeleccionarTablero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.SeleccionarTableroResponse> ProyectoEscritorio.TableroWS.TableroWS.SeleccionarTableroAsync(ProyectoEscritorio.TableroWS.SeleccionarTableroRequest request) {
            return base.Channel.SeleccionarTableroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.TableroWS.SeleccionarTableroResponse> SeleccionarTableroAsync(int id) {
            ProyectoEscritorio.TableroWS.SeleccionarTableroRequest inValue = new ProyectoEscritorio.TableroWS.SeleccionarTableroRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.TableroWS.TableroWS)(this)).SeleccionarTableroAsync(inValue);
        }
    }
}
