//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.ModuloWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="ModuloWS.ModuloWS")]
    public interface ModuloWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/AgregarModuloRequest", ReplyAction="http://webservices/ModuloWS/AgregarModuloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModuloWS.AgregarModuloResponse AgregarModulo(ProyectoEscritorio.ModuloWS.AgregarModuloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/AgregarModuloRequest", ReplyAction="http://webservices/ModuloWS/AgregarModuloResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.AgregarModuloResponse> AgregarModuloAsync(ProyectoEscritorio.ModuloWS.AgregarModuloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/EliminarModuloRequest", ReplyAction="http://webservices/ModuloWS/EliminarModuloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModuloWS.EliminarModuloResponse EliminarModulo(ProyectoEscritorio.ModuloWS.EliminarModuloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/EliminarModuloRequest", ReplyAction="http://webservices/ModuloWS/EliminarModuloResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EliminarModuloResponse> EliminarModuloAsync(ProyectoEscritorio.ModuloWS.EliminarModuloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/EditarModuloRequest", ReplyAction="http://webservices/ModuloWS/EditarModuloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModuloWS.EditarModuloResponse EditarModulo(ProyectoEscritorio.ModuloWS.EditarModuloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/EditarModuloRequest", ReplyAction="http://webservices/ModuloWS/EditarModuloResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EditarModuloResponse> EditarModuloAsync(ProyectoEscritorio.ModuloWS.EditarModuloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/SeleccionarModuloRequest", ReplyAction="http://webservices/ModuloWS/SeleccionarModuloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModuloWS.SeleccionarModuloResponse SeleccionarModulo(ProyectoEscritorio.ModuloWS.SeleccionarModuloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/SeleccionarModuloRequest", ReplyAction="http://webservices/ModuloWS/SeleccionarModuloResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.SeleccionarModuloResponse> SeleccionarModuloAsync(ProyectoEscritorio.ModuloWS.SeleccionarModuloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/ObtenerModulosDeTableroRequest", ReplyAction="http://webservices/ModuloWS/ObtenerModulosDeTableroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroResponse ObtenerModulosDeTablero(ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/ObtenerModulosDeTableroRequest", ReplyAction="http://webservices/ModuloWS/ObtenerModulosDeTableroResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroResponse> ObtenerModulosDeTableroAsync(ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/EliminarModuloVirtualRequest", ReplyAction="http://webservices/ModuloWS/EliminarModuloVirtualResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.ModuloWS.EliminarModuloVirtualResponse EliminarModuloVirtual(ProyectoEscritorio.ModuloWS.EliminarModuloVirtualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ModuloWS/EliminarModuloVirtualRequest", ReplyAction="http://webservices/ModuloWS/EliminarModuloVirtualResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EliminarModuloVirtualResponse> EliminarModuloVirtualAsync(ProyectoEscritorio.ModuloWS.EliminarModuloVirtualRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarModulo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarModuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTablero;
        
        public AgregarModuloRequest() {
        }
        
        public AgregarModuloRequest(string nombre, int idTablero) {
            this.nombre = nombre;
            this.idTablero = idTablero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarModuloResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarModuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public AgregarModuloResponse() {
        }
        
        public AgregarModuloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarModulo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarModuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarModuloRequest() {
        }
        
        public EliminarModuloRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarModuloResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarModuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarModuloResponse() {
        }
        
        public EliminarModuloResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarModulo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarModuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EditarModuloRequest() {
        }
        
        public EditarModuloRequest(string nombre, int id) {
            this.nombre = nombre;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditarModuloResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EditarModuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EditarModuloResponse() {
        }
        
        public EditarModuloResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class modulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idField;
        
        private int idTableroField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTablero {
            get {
                return this.idTableroField;
            }
            set {
                this.idTableroField = value;
                this.RaisePropertyChanged("idTablero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarModulo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarModuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarModuloRequest() {
        }
        
        public SeleccionarModuloRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarModuloResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarModuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ModuloWS.modulo @return;
        
        public SeleccionarModuloResponse() {
        }
        
        public SeleccionarModuloResponse(ProyectoEscritorio.ModuloWS.modulo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerModulosDeTablero", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerModulosDeTableroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTablero;
        
        public ObtenerModulosDeTableroRequest() {
        }
        
        public ObtenerModulosDeTableroRequest(int idTablero) {
            this.idTablero = idTablero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerModulosDeTableroResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerModulosDeTableroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.ModuloWS.modulo[] @return;
        
        public ObtenerModulosDeTableroResponse() {
        }
        
        public ObtenerModulosDeTableroResponse(ProyectoEscritorio.ModuloWS.modulo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarModuloVirtual", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarModuloVirtualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarModuloVirtualRequest() {
        }
        
        public EliminarModuloVirtualRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarModuloVirtualResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarModuloVirtualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarModuloVirtualResponse() {
        }
        
        public EliminarModuloVirtualResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ModuloWSChannel : ProyectoEscritorio.ModuloWS.ModuloWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuloWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.ModuloWS.ModuloWS>, ProyectoEscritorio.ModuloWS.ModuloWS {
        
        public ModuloWSClient() {
        }
        
        public ModuloWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuloWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuloWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuloWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModuloWS.AgregarModuloResponse ProyectoEscritorio.ModuloWS.ModuloWS.AgregarModulo(ProyectoEscritorio.ModuloWS.AgregarModuloRequest request) {
            return base.Channel.AgregarModulo(request);
        }
        
        public int AgregarModulo(string nombre, int idTablero) {
            ProyectoEscritorio.ModuloWS.AgregarModuloRequest inValue = new ProyectoEscritorio.ModuloWS.AgregarModuloRequest();
            inValue.nombre = nombre;
            inValue.idTablero = idTablero;
            ProyectoEscritorio.ModuloWS.AgregarModuloResponse retVal = ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).AgregarModulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.AgregarModuloResponse> ProyectoEscritorio.ModuloWS.ModuloWS.AgregarModuloAsync(ProyectoEscritorio.ModuloWS.AgregarModuloRequest request) {
            return base.Channel.AgregarModuloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.AgregarModuloResponse> AgregarModuloAsync(string nombre, int idTablero) {
            ProyectoEscritorio.ModuloWS.AgregarModuloRequest inValue = new ProyectoEscritorio.ModuloWS.AgregarModuloRequest();
            inValue.nombre = nombre;
            inValue.idTablero = idTablero;
            return ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).AgregarModuloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModuloWS.EliminarModuloResponse ProyectoEscritorio.ModuloWS.ModuloWS.EliminarModulo(ProyectoEscritorio.ModuloWS.EliminarModuloRequest request) {
            return base.Channel.EliminarModulo(request);
        }
        
        public bool EliminarModulo(int id) {
            ProyectoEscritorio.ModuloWS.EliminarModuloRequest inValue = new ProyectoEscritorio.ModuloWS.EliminarModuloRequest();
            inValue.id = id;
            ProyectoEscritorio.ModuloWS.EliminarModuloResponse retVal = ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).EliminarModulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EliminarModuloResponse> ProyectoEscritorio.ModuloWS.ModuloWS.EliminarModuloAsync(ProyectoEscritorio.ModuloWS.EliminarModuloRequest request) {
            return base.Channel.EliminarModuloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EliminarModuloResponse> EliminarModuloAsync(int id) {
            ProyectoEscritorio.ModuloWS.EliminarModuloRequest inValue = new ProyectoEscritorio.ModuloWS.EliminarModuloRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).EliminarModuloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModuloWS.EditarModuloResponse ProyectoEscritorio.ModuloWS.ModuloWS.EditarModulo(ProyectoEscritorio.ModuloWS.EditarModuloRequest request) {
            return base.Channel.EditarModulo(request);
        }
        
        public bool EditarModulo(string nombre, int id) {
            ProyectoEscritorio.ModuloWS.EditarModuloRequest inValue = new ProyectoEscritorio.ModuloWS.EditarModuloRequest();
            inValue.nombre = nombre;
            inValue.id = id;
            ProyectoEscritorio.ModuloWS.EditarModuloResponse retVal = ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).EditarModulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EditarModuloResponse> ProyectoEscritorio.ModuloWS.ModuloWS.EditarModuloAsync(ProyectoEscritorio.ModuloWS.EditarModuloRequest request) {
            return base.Channel.EditarModuloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EditarModuloResponse> EditarModuloAsync(string nombre, int id) {
            ProyectoEscritorio.ModuloWS.EditarModuloRequest inValue = new ProyectoEscritorio.ModuloWS.EditarModuloRequest();
            inValue.nombre = nombre;
            inValue.id = id;
            return ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).EditarModuloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModuloWS.SeleccionarModuloResponse ProyectoEscritorio.ModuloWS.ModuloWS.SeleccionarModulo(ProyectoEscritorio.ModuloWS.SeleccionarModuloRequest request) {
            return base.Channel.SeleccionarModulo(request);
        }
        
        public ProyectoEscritorio.ModuloWS.modulo SeleccionarModulo(int id) {
            ProyectoEscritorio.ModuloWS.SeleccionarModuloRequest inValue = new ProyectoEscritorio.ModuloWS.SeleccionarModuloRequest();
            inValue.id = id;
            ProyectoEscritorio.ModuloWS.SeleccionarModuloResponse retVal = ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).SeleccionarModulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.SeleccionarModuloResponse> ProyectoEscritorio.ModuloWS.ModuloWS.SeleccionarModuloAsync(ProyectoEscritorio.ModuloWS.SeleccionarModuloRequest request) {
            return base.Channel.SeleccionarModuloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.SeleccionarModuloResponse> SeleccionarModuloAsync(int id) {
            ProyectoEscritorio.ModuloWS.SeleccionarModuloRequest inValue = new ProyectoEscritorio.ModuloWS.SeleccionarModuloRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).SeleccionarModuloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroResponse ProyectoEscritorio.ModuloWS.ModuloWS.ObtenerModulosDeTablero(ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroRequest request) {
            return base.Channel.ObtenerModulosDeTablero(request);
        }
        
        public ProyectoEscritorio.ModuloWS.modulo[] ObtenerModulosDeTablero(int idTablero) {
            ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroRequest inValue = new ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroRequest();
            inValue.idTablero = idTablero;
            ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroResponse retVal = ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).ObtenerModulosDeTablero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroResponse> ProyectoEscritorio.ModuloWS.ModuloWS.ObtenerModulosDeTableroAsync(ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroRequest request) {
            return base.Channel.ObtenerModulosDeTableroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroResponse> ObtenerModulosDeTableroAsync(int idTablero) {
            ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroRequest inValue = new ProyectoEscritorio.ModuloWS.ObtenerModulosDeTableroRequest();
            inValue.idTablero = idTablero;
            return ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).ObtenerModulosDeTableroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.ModuloWS.EliminarModuloVirtualResponse ProyectoEscritorio.ModuloWS.ModuloWS.EliminarModuloVirtual(ProyectoEscritorio.ModuloWS.EliminarModuloVirtualRequest request) {
            return base.Channel.EliminarModuloVirtual(request);
        }
        
        public bool EliminarModuloVirtual(int id) {
            ProyectoEscritorio.ModuloWS.EliminarModuloVirtualRequest inValue = new ProyectoEscritorio.ModuloWS.EliminarModuloVirtualRequest();
            inValue.id = id;
            ProyectoEscritorio.ModuloWS.EliminarModuloVirtualResponse retVal = ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).EliminarModuloVirtual(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EliminarModuloVirtualResponse> ProyectoEscritorio.ModuloWS.ModuloWS.EliminarModuloVirtualAsync(ProyectoEscritorio.ModuloWS.EliminarModuloVirtualRequest request) {
            return base.Channel.EliminarModuloVirtualAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.ModuloWS.EliminarModuloVirtualResponse> EliminarModuloVirtualAsync(int id) {
            ProyectoEscritorio.ModuloWS.EliminarModuloVirtualRequest inValue = new ProyectoEscritorio.ModuloWS.EliminarModuloVirtualRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.ModuloWS.ModuloWS)(this)).EliminarModuloVirtualAsync(inValue);
        }
    }
}
