//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEscritorio.EquipoUsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="EquipoUsuarioWS.EquipoUsuarioWS")]
    public interface EquipoUsuarioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/AgregarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/AgregarEquipoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioResponse AgregarEquipoUsuario(ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/AgregarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/AgregarEquipoUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioResponse> AgregarEquipoUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/EliminarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/EliminarEquipoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioResponse EliminarEquipoUsuario(ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/EliminarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/EliminarEquipoUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioResponse> EliminarEquipoUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/SeleccionarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/SeleccionarEquipoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioResponse SeleccionarEquipoUsuario(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/SeleccionarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/SeleccionarEquipoUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioResponse> SeleccionarEquipoUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/ObtenerEquiposDeUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/ObtenerEquiposDeUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioResponse ObtenerEquiposDeUsuario(ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/ObtenerEquiposDeUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/ObtenerEquiposDeUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioResponse> ObtenerEquiposDeUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/ObtenerUsuariosDeEquipoRequest", ReplyAction="http://webservices/EquipoUsuarioWS/ObtenerUsuariosDeEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoResponse ObtenerUsuariosDeEquipo(ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/ObtenerUsuariosDeEquipoRequest", ReplyAction="http://webservices/EquipoUsuarioWS/ObtenerUsuariosDeEquipoResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoResponse> ObtenerUsuariosDeEquipoAsync(ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/SeleccionarIdPorEquipoYUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/SeleccionarIdPorEquipoYUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioResponse SeleccionarIdPorEquipoYUsuario(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/SeleccionarIdPorEquipoYUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/SeleccionarIdPorEquipoYUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioResponse> SeleccionarIdPorEquipoYUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/SeleccionarTodosEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/SeleccionarTodosEquipoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioResponse SeleccionarTodosEquipoUsuario(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/SeleccionarTodosEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/SeleccionarTodosEquipoUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioResponse> SeleccionarTodosEquipoUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarEquipoUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarEquipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEquipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rol;
        
        public AgregarEquipoUsuarioRequest() {
        }
        
        public AgregarEquipoUsuarioRequest(int idEquipo, int idUsuario, string rol) {
            this.idEquipo = idEquipo;
            this.idUsuario = idUsuario;
            this.rol = rol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarEquipoUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarEquipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public AgregarEquipoUsuarioResponse() {
        }
        
        public AgregarEquipoUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarEquipoUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarEquipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarEquipoUsuarioRequest() {
        }
        
        public EliminarEquipoUsuarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarEquipoUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarEquipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarEquipoUsuarioResponse() {
        }
        
        public EliminarEquipoUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class equipoUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int idEquipoField;
        
        private int idUsuarioField;
        
        private string rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEquipo {
            get {
                return this.idEquipoField;
            }
            set {
                this.idEquipoField = value;
                this.RaisePropertyChanged("idEquipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contrasenaField;
        
        private string emailField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class equipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarEquipoUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarEquipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarEquipoUsuarioRequest() {
        }
        
        public SeleccionarEquipoUsuarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarEquipoUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarEquipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.EquipoUsuarioWS.equipoUsuario @return;
        
        public SeleccionarEquipoUsuarioResponse() {
        }
        
        public SeleccionarEquipoUsuarioResponse(ProyectoEscritorio.EquipoUsuarioWS.equipoUsuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerEquiposDeUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerEquiposDeUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public ObtenerEquiposDeUsuarioRequest() {
        }
        
        public ObtenerEquiposDeUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerEquiposDeUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerEquiposDeUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.EquipoUsuarioWS.equipo[] @return;
        
        public ObtenerEquiposDeUsuarioResponse() {
        }
        
        public ObtenerEquiposDeUsuarioResponse(ProyectoEscritorio.EquipoUsuarioWS.equipo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuariosDeEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerUsuariosDeEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEquipo;
        
        public ObtenerUsuariosDeEquipoRequest() {
        }
        
        public ObtenerUsuariosDeEquipoRequest(int idEquipo) {
            this.idEquipo = idEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuariosDeEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerUsuariosDeEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.EquipoUsuarioWS.usuario[] @return;
        
        public ObtenerUsuariosDeEquipoResponse() {
        }
        
        public ObtenerUsuariosDeEquipoResponse(ProyectoEscritorio.EquipoUsuarioWS.usuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarIdPorEquipoYUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarIdPorEquipoYUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEquipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public SeleccionarIdPorEquipoYUsuarioRequest() {
        }
        
        public SeleccionarIdPorEquipoYUsuarioRequest(int idEquipo, int idUsuario) {
            this.idEquipo = idEquipo;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarIdPorEquipoYUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarIdPorEquipoYUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public SeleccionarIdPorEquipoYUsuarioResponse() {
        }
        
        public SeleccionarIdPorEquipoYUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarTodosEquipoUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarTodosEquipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEquipo;
        
        public SeleccionarTodosEquipoUsuarioRequest() {
        }
        
        public SeleccionarTodosEquipoUsuarioRequest(int idEquipo) {
            this.idEquipo = idEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarTodosEquipoUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarTodosEquipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoEscritorio.EquipoUsuarioWS.equipoUsuario[] @return;
        
        public SeleccionarTodosEquipoUsuarioResponse() {
        }
        
        public SeleccionarTodosEquipoUsuarioResponse(ProyectoEscritorio.EquipoUsuarioWS.equipoUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EquipoUsuarioWSChannel : ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquipoUsuarioWSClient : System.ServiceModel.ClientBase<ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS>, ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS {
        
        public EquipoUsuarioWSClient() {
        }
        
        public EquipoUsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquipoUsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipoUsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipoUsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioResponse ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.AgregarEquipoUsuario(ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioRequest request) {
            return base.Channel.AgregarEquipoUsuario(request);
        }
        
        public int AgregarEquipoUsuario(int idEquipo, int idUsuario, string rol) {
            ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioRequest();
            inValue.idEquipo = idEquipo;
            inValue.idUsuario = idUsuario;
            inValue.rol = rol;
            ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioResponse retVal = ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).AgregarEquipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioResponse> ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.AgregarEquipoUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioRequest request) {
            return base.Channel.AgregarEquipoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioResponse> AgregarEquipoUsuarioAsync(int idEquipo, int idUsuario, string rol) {
            ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.AgregarEquipoUsuarioRequest();
            inValue.idEquipo = idEquipo;
            inValue.idUsuario = idUsuario;
            inValue.rol = rol;
            return ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).AgregarEquipoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioResponse ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.EliminarEquipoUsuario(ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioRequest request) {
            return base.Channel.EliminarEquipoUsuario(request);
        }
        
        public bool EliminarEquipoUsuario(int id) {
            ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioRequest();
            inValue.id = id;
            ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioResponse retVal = ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).EliminarEquipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioResponse> ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.EliminarEquipoUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioRequest request) {
            return base.Channel.EliminarEquipoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioResponse> EliminarEquipoUsuarioAsync(int id) {
            ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.EliminarEquipoUsuarioRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).EliminarEquipoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioResponse ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.SeleccionarEquipoUsuario(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioRequest request) {
            return base.Channel.SeleccionarEquipoUsuario(request);
        }
        
        public ProyectoEscritorio.EquipoUsuarioWS.equipoUsuario SeleccionarEquipoUsuario(int id) {
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioRequest();
            inValue.id = id;
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioResponse retVal = ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).SeleccionarEquipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioResponse> ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.SeleccionarEquipoUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioRequest request) {
            return base.Channel.SeleccionarEquipoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioResponse> SeleccionarEquipoUsuarioAsync(int id) {
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.SeleccionarEquipoUsuarioRequest();
            inValue.id = id;
            return ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).SeleccionarEquipoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioResponse ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.ObtenerEquiposDeUsuario(ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioRequest request) {
            return base.Channel.ObtenerEquiposDeUsuario(request);
        }
        
        public ProyectoEscritorio.EquipoUsuarioWS.equipo[] ObtenerEquiposDeUsuario(int idUsuario) {
            ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioResponse retVal = ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).ObtenerEquiposDeUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioResponse> ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.ObtenerEquiposDeUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioRequest request) {
            return base.Channel.ObtenerEquiposDeUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioResponse> ObtenerEquiposDeUsuarioAsync(int idUsuario) {
            ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.ObtenerEquiposDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).ObtenerEquiposDeUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoResponse ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.ObtenerUsuariosDeEquipo(ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoRequest request) {
            return base.Channel.ObtenerUsuariosDeEquipo(request);
        }
        
        public ProyectoEscritorio.EquipoUsuarioWS.usuario[] ObtenerUsuariosDeEquipo(int idEquipo) {
            ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoRequest();
            inValue.idEquipo = idEquipo;
            ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoResponse retVal = ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).ObtenerUsuariosDeEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoResponse> ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.ObtenerUsuariosDeEquipoAsync(ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoRequest request) {
            return base.Channel.ObtenerUsuariosDeEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoResponse> ObtenerUsuariosDeEquipoAsync(int idEquipo) {
            ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.ObtenerUsuariosDeEquipoRequest();
            inValue.idEquipo = idEquipo;
            return ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).ObtenerUsuariosDeEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioResponse ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuario(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioRequest request) {
            return base.Channel.SeleccionarIdPorEquipoYUsuario(request);
        }
        
        public int SeleccionarIdPorEquipoYUsuario(int idEquipo, int idUsuario) {
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioRequest();
            inValue.idEquipo = idEquipo;
            inValue.idUsuario = idUsuario;
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioResponse retVal = ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).SeleccionarIdPorEquipoYUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioResponse> ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioRequest request) {
            return base.Channel.SeleccionarIdPorEquipoYUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioResponse> SeleccionarIdPorEquipoYUsuarioAsync(int idEquipo, int idUsuario) {
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.SeleccionarIdPorEquipoYUsuarioRequest();
            inValue.idEquipo = idEquipo;
            inValue.idUsuario = idUsuario;
            return ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).SeleccionarIdPorEquipoYUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioResponse ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.SeleccionarTodosEquipoUsuario(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioRequest request) {
            return base.Channel.SeleccionarTodosEquipoUsuario(request);
        }
        
        public ProyectoEscritorio.EquipoUsuarioWS.equipoUsuario[] SeleccionarTodosEquipoUsuario(int idEquipo) {
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioRequest();
            inValue.idEquipo = idEquipo;
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioResponse retVal = ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).SeleccionarTodosEquipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioResponse> ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioAsync(ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioRequest request) {
            return base.Channel.SeleccionarTodosEquipoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioResponse> SeleccionarTodosEquipoUsuarioAsync(int idEquipo) {
            ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioRequest inValue = new ProyectoEscritorio.EquipoUsuarioWS.SeleccionarTodosEquipoUsuarioRequest();
            inValue.idEquipo = idEquipo;
            return ((ProyectoEscritorio.EquipoUsuarioWS.EquipoUsuarioWS)(this)).SeleccionarTodosEquipoUsuarioAsync(inValue);
        }
    }
}
